In [ ]:
# Get the dataset
!wget https://raw.githubusercontent.com/karpathy/ng-video-lecture/refs/heads/master/input.txt

--2026-06-04 19:45:37--  https://raw.githubusercontent.com/karpathy/ng-video-lecture/refs/heads/master/input.txt
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1115394 (1.1M) [text/plain]
Saving to: ‘input.txt.1’

input.txt.1         100%[===================>]   1.06M  --.-KB/s    in 0.01s   

2026-06-04 19:45:37 (111 MB/s) - ‘input.txt.1’ saved [1115394/1115394]



In [ ]:
with open('input.txt', 'r') as f:
  text = f.read()

In [ ]:
print(f'length of the dataset in characters we have: {len(text)}')

length of the dataset in characters we have: 1115394


In [ ]:
# Look at the first 1000 characters of the dataset
print(text[:1000])

First Citizen:
Before we proceed any further, hear me speak.

All:
Speak, speak.

First Citizen:
You are all resolved rather to die than to famish?

All:
Resolved. resolved.

First Citizen:
First, you know Caius Marcius is chief enemy to the people.

All:
We know't, we know't.

First Citizen:
Let us kill him, and we'll have corn at our own price.
Is't a verdict?

All:
No more talking on't; let it be done: away, away!

Second Citizen:
One word, good citizens.

First Citizen:
We are accounted poor citizens, the patricians good.
What authority surfeits on would relieve us: if they
would yield us but the superfluity, while it were
wholesome, we might guess they relieved us humanely;
but they think we are too dear: the leanness that
afflicts us, the object of our misery, is as an
inventory to particularise their abundance; our
sufferance is a gain to them Let us revenge this with
our pikes, ere we become rakes: for the gods know I
speak this in hunger for bread, not in thirst for revenge.



In [ ]:
# here are all the unique characters that occurs in the text

chars = sorted(list(set(text))) # getting every characters using set adn making a list and sorting them
# print(char)
vocab_size = len(chars) # -> 65
print(''.join(chars)) # without join we'd get coma separated characters
vocab_size


 !$&',-.3:;?ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz


65

In [ ]:
# tokenize the text - transforming individual characters into integers

# Why enumerate? because it allows us to get both the index and the value in a list

for i, ch in enumerate(chars):
  print({ch:i})

{'\n': 0}
{' ': 1}
{'!': 2}
{'$': 3}
{'&': 4}
{"'": 5}
{',': 6}
{'-': 7}
{'.': 8}
{'3': 9}
{':': 10}
{';': 11}
{'?': 12}
{'A': 13}
{'B': 14}
{'C': 15}
{'D': 16}
{'E': 17}
{'F': 18}
{'G': 19}
{'H': 20}
{'I': 21}
{'J': 22}
{'K': 23}
{'L': 24}
{'M': 25}
{'N': 26}
{'O': 27}
{'P': 28}
{'Q': 29}
{'R': 30}
{'S': 31}
{'T': 32}
{'U': 33}
{'V': 34}
{'W': 35}
{'X': 36}
{'Y': 37}
{'Z': 38}
{'a': 39}
{'b': 40}
{'c': 41}
{'d': 42}
{'e': 43}
{'f': 44}
{'g': 45}
{'h': 46}
{'i': 47}
{'j': 48}
{'k': 49}
{'l': 50}
{'m': 51}
{'n': 52}
{'o': 53}
{'p': 54}
{'q': 55}
{'r': 56}
{'s': 57}
{'t': 58}
{'u': 59}
{'v': 60}
{'w': 61}
{'x': 62}
{'y': 63}
{'z': 64}


In [ ]:
for i, ch in enumerate(chars):
  print({i:ch})

{0: '\n'}
{1: ' '}
{2: '!'}
{3: '$'}
{4: '&'}
{5: "'"}
{6: ','}
{7: '-'}
{8: '.'}
{9: '3'}
{10: ':'}
{11: ';'}
{12: '?'}
{13: 'A'}
{14: 'B'}
{15: 'C'}
{16: 'D'}
{17: 'E'}
{18: 'F'}
{19: 'G'}
{20: 'H'}
{21: 'I'}
{22: 'J'}
{23: 'K'}
{24: 'L'}
{25: 'M'}
{26: 'N'}
{27: 'O'}
{28: 'P'}
{29: 'Q'}
{30: 'R'}
{31: 'S'}
{32: 'T'}
{33: 'U'}
{34: 'V'}
{35: 'W'}
{36: 'X'}
{37: 'Y'}
{38: 'Z'}
{39: 'a'}
{40: 'b'}
{41: 'c'}
{42: 'd'}
{43: 'e'}
{44: 'f'}
{45: 'g'}
{46: 'h'}
{47: 'i'}
{48: 'j'}
{49: 'k'}
{50: 'l'}
{51: 'm'}
{52: 'n'}
{53: 'o'}
{54: 'p'}
{55: 'q'}
{56: 'r'}
{57: 's'}
{58: 't'}
{59: 'u'}
{60: 'v'}
{61: 'w'}
{62: 'x'}
{63: 'y'}
{64: 'z'}


In [ ]:
# stoi -> string to integer
#itos -> integer to string

stoi = {ch:i for i, ch in enumerate(chars)}
itos = {i:ch for i, ch in enumerate(chars)}
print(stoi, '\n', itos)

{'\n': 0, ' ': 1, '!': 2, '$': 3, '&': 4, "'": 5, ',': 6, '-': 7, '.': 8, '3': 9, ':': 10, ';': 11, '?': 12, 'A': 13, 'B': 14, 'C': 15, 'D': 16, 'E': 17, 'F': 18, 'G': 19, 'H': 20, 'I': 21, 'J': 22, 'K': 23, 'L': 24, 'M': 25, 'N': 26, 'O': 27, 'P': 28, 'Q': 29, 'R': 30, 'S': 31, 'T': 32, 'U': 33, 'V': 34, 'W': 35, 'X': 36, 'Y': 37, 'Z': 38, 'a': 39, 'b': 40, 'c': 41, 'd': 42, 'e': 43, 'f': 44, 'g': 45, 'h': 46, 'i': 47, 'j': 48, 'k': 49, 'l': 50, 'm': 51, 'n': 52, 'o': 53, 'p': 54, 'q': 55, 'r': 56, 's': 57, 't': 58, 'u': 59, 'v': 60, 'w': 61, 'x': 62, 'y': 63, 'z': 64} 
 {0: '\n', 1: ' ', 2: '!', 3: '$', 4: '&', 5: "'", 6: ',', 7: '-', 8: '.', 9: '3', 10: ':', 11: ';', 12: '?', 13: 'A', 14: 'B', 15: 'C', 16: 'D', 17: 'E', 18: 'F', 19: 'G', 20: 'H', 21: 'I', 22: 'J', 23: 'K', 24: 'L', 25: 'M', 26: 'N', 27: 'O', 28: 'P', 29: 'Q', 30: 'R', 31: 'S', 32: 'T', 33: 'U', 34: 'V', 35: 'W', 36: 'X', 37: 'Y', 38: 'Z', 39: 'a', 40: 'b', 41: 'c', 42: 'd', 43: 'e', 44: 'f', 45: 'g', 46: 'h', 47: 'i

In [ ]:
# encoder: take a string, output a list of integers
encode = lambda string : [stoi[c] for c in string]

# encode is the name of the function
# string is the argument
# stoi[c] is return statement
# for c in string is the loop
'''
It is equivalent to:

def encodev1(string):
  encode_list = []
  for c in string:
    encode_list.append(stoi[c])
  return encode_list
'''


'\nIt is equivalent to:\n\ndef encodev1(string):\n  encode_list = []\n  for c in string:\n    encode_list.append(stoi[c])\n  return encode_list\n'

In [ ]:
encode('hello world')

[46, 43, 50, 50, 53, 1, 61, 53, 56, 50, 42]

In [ ]:
# decode: take a liat of integers, output a string
decode = lambda integers : ''.join([itos[i] for i in integers])
decode

<function __main__.<lambda>(integers)>

In [ ]:
decode(encode('hello world'))

'hello world'

In [ ]:
# encode the entire dataset and store it in torch.Tensor
import torch

data = torch.tensor(encode(text), dtype = torch.long) # We have stored the input.txt in text in the first cell
print(data[:1000],'\n') # see the encoded version of the first 1000 characters in the encoded form
print(data.shape, '\t', data.dtype)

tensor([18, 47, 56, 57, 58,  1, 15, 47, 58, 47, 64, 43, 52, 10,  0, 14, 43, 44,
        53, 56, 43,  1, 61, 43,  1, 54, 56, 53, 41, 43, 43, 42,  1, 39, 52, 63,
         1, 44, 59, 56, 58, 46, 43, 56,  6,  1, 46, 43, 39, 56,  1, 51, 43,  1,
        57, 54, 43, 39, 49,  8,  0,  0, 13, 50, 50, 10,  0, 31, 54, 43, 39, 49,
         6,  1, 57, 54, 43, 39, 49,  8,  0,  0, 18, 47, 56, 57, 58,  1, 15, 47,
        58, 47, 64, 43, 52, 10,  0, 37, 53, 59,  1, 39, 56, 43,  1, 39, 50, 50,
         1, 56, 43, 57, 53, 50, 60, 43, 42,  1, 56, 39, 58, 46, 43, 56,  1, 58,
        53,  1, 42, 47, 43,  1, 58, 46, 39, 52,  1, 58, 53,  1, 44, 39, 51, 47,
        57, 46, 12,  0,  0, 13, 50, 50, 10,  0, 30, 43, 57, 53, 50, 60, 43, 42,
         8,  1, 56, 43, 57, 53, 50, 60, 43, 42,  8,  0,  0, 18, 47, 56, 57, 58,
         1, 15, 47, 58, 47, 64, 43, 52, 10,  0, 18, 47, 56, 57, 58,  6,  1, 63,
        53, 59,  1, 49, 52, 53, 61,  1, 15, 39, 47, 59, 57,  1, 25, 39, 56, 41,
        47, 59, 57,  1, 47, 57,  1, 41, 

In [ ]:
# let's now split the data into train and validation sets

# n = 0.9 * len(data) -> this would give float value
# n
n = int(0.9 * len(data))
train_data = data[:n] # first 90& of data would go in training data and rest in the val data.
val_data = data[n:]
print(f'\n length of train data: {len(train_data)} \n length of validation data: {len(val_data)}')


 length of train data: 1003854 
 length of validation data: 111540


In [ ]:
 # sending the text to the transformers so it can learn and train those patterns. But sending
 # altogether is not computationally feasible.
# that's why we use block_size / context length to sample random chunks from the text
block_size = 8

train_data[:block_size + 1]

tensor([18, 47, 56, 57, 58,  1, 15, 47, 58])

In [ ]:
x = train_data[:block_size]
y = train_data[1:block_size+1]
print(x, y)

tensor([18, 47, 56, 57, 58,  1, 15, 47]) tensor([47, 56, 57, 58,  1, 15, 47, 58])


In [ ]:
print(text[block_size])

t


In [ ]:
for t in range(block_size):
  context = x[:t+1]
  target = y[t]

  print(f'When input/the current character is {context} \t the target/next character is: {target}')

When input/the current character is tensor([18]) 	 the target/next character is: 47
When input/the current character is tensor([18, 47]) 	 the target/next character is: 56
When input/the current character is tensor([18, 47, 56]) 	 the target/next character is: 57
When input/the current character is tensor([18, 47, 56, 57]) 	 the target/next character is: 58
When input/the current character is tensor([18, 47, 56, 57, 58]) 	 the target/next character is: 1
When input/the current character is tensor([18, 47, 56, 57, 58,  1]) 	 the target/next character is: 15
When input/the current character is tensor([18, 47, 56, 57, 58,  1, 15]) 	 the target/next character is: 47
When input/the current character is tensor([18, 47, 56, 57, 58,  1, 15, 47]) 	 the target/next character is: 58


In [ ]:
torch.manual_seed(42)

batch_size = 4 # how many independent sequences will we process in parallel?

block_size = 8 # what is the maximum context length for the prediction?

def get_batch(split):

  # generate a small batch of data of inputs x and targets y
  data = train_data if split == 'train' else val_data

  ix = torch.randint(len(data) - block_size, (batch_size,))

  x = torch.stack([data[i : i + block_size] for i in ix])

  y = torch.stack([data[i + 1 : i + block_size + 1] for i in ix])

  return x, y

xb, yb = get_batch('train')

print("inputs:")
print(xb.shape)
print(xb)

print('targets:')
print(yb.shape)
print(yb)

print('----')

for b in range(batch_size): # batch dimension

  for t in range(block_size): # time dimension

      context = xb[b, : t + 1]
      target = yb[b, t]

      print(f'When input/the current character is {context.tolist()} the target/next character is: {target}')

inputs:
torch.Size([4, 8])
tensor([[57,  1, 46, 47, 57,  1, 50, 53],
        [ 1, 58, 46, 43, 56, 43,  1, 41],
        [17, 26, 15, 17, 10,  0, 32, 53],
        [57, 58,  6,  1, 61, 47, 58, 46]])
targets:
torch.Size([4, 8])
tensor([[ 1, 46, 47, 57,  1, 50, 53, 60],
        [58, 46, 43, 56, 43,  1, 41, 39],
        [26, 15, 17, 10,  0, 32, 53,  1],
        [58,  6,  1, 61, 47, 58, 46,  0]])
----
When input/the current character is [57] the target/next character is: 1
When input/the current character is [57, 1] the target/next character is: 46
When input/the current character is [57, 1, 46] the target/next character is: 47
When input/the current character is [57, 1, 46, 47] the target/next character is: 57
When input/the current character is [57, 1, 46, 47, 57] the target/next character is: 1
When input/the current character is [57, 1, 46, 47, 57, 1] the target/next character is: 50
When input/the current character is [57, 1, 46, 47, 57, 1, 50] the target/next character is: 53
When input

In [ ]:
batch_size = 4
ix = torch.randint(len(train_data) - block_size, (batch_size,)) # randint takes the lower values as 0 by default.
# We just need to mention the higher value like 0 to higher value and then the size.
# Here, (batch_size,) is a 1D vector so we would get 4 random integers in a 1D form
print(ix)

tensor([848200, 920925, 369014, 633086])


In [ ]:
len(train_data)

1003854

In [ ]:
random = torch.randint(10, (5,))
random

tensor([0, 3, 8, 4, 0])

In [ ]:
d = [2, 4, 3, 6, 7, 10, 12, 11, 8, 9, 1, 13, 15, 16, 14, 17, 19, 18, 5, 0] # encoded data
bs = 4 # batch_size
bls = 5 # block_size

In [ ]:
len(d)

20

In [ ]:
ixx = torch.randint(len(d) - bls, (bs,)) # -> ixx = ((20 - 5), (4,)) -> ixx = (15, (4,)) -> ixx = (low=0, high=15, size=(4,)) -> 1D vector of 4 random elements in a list of a range of o to 15
len(ixx)

4

In [ ]:
ixx

tensor([9, 6, 7, 5])

In [ ]:
for i in ixx: # we are looping through directly ixx instead of using range and len that's why
# we would get the exact value in ixx instead of the index
  print(f'when i = {i}: \n')
  xx = d[i : i + bls]
  print(xx)
  print("\n")

when i = 9: 

[9, 1, 13, 15, 16]


when i = 6: 

[12, 11, 8, 9, 1]


when i = 7: 

[11, 8, 9, 1, 13]


when i = 5: 

[10, 12, 11, 8, 9]




In [ ]:
for i in ixx:
  print(f'when i = {i}: \n')
  yy = d[i+1 : i + bls + 1]
  print(yy)
  print("\n")

when i = 9: 

[1, 13, 15, 16, 14]


when i = 6: 

[11, 8, 9, 1, 13]


when i = 7: 

[8, 9, 1, 13, 15]


when i = 5: 

[12, 11, 8, 9, 1]




In [ ]:
l = [1, 5, 6, 7, 3]
l

[1, 5, 6, 7, 3]

In [ ]:
for i in l:
  print(i)

1
5
6
7
3


In [ ]:
s = 'hello world'
for i in s:
  print(i)

h
e
l
l
o
 
w
o
r
l
d


In [ ]:
ixx

tensor([9, 6, 7, 5])

In [ ]:
for i in ixx:
  xx = d[i : i + bls]
  yy = d[i + 1 : i + bls + 1]

  print(f'i = {i} \n')
  print(f'xx = {xx} \n')
  print(f'yy = {yy} \n')
  print()

i = 9 

xx = [9, 1, 13, 15, 16] 

yy = [1, 13, 15, 16, 14] 


i = 6 

xx = [12, 11, 8, 9, 1] 

yy = [11, 8, 9, 1, 13] 


i = 7 

xx = [11, 8, 9, 1, 13] 

yy = [8, 9, 1, 13, 15] 


i = 5 

xx = [10, 12, 11, 8, 9] 

yy = [12, 11, 8, 9, 1] 




In [ ]:
l1 = [2, 5, 6, 4, 7, 9, 8, 12]
for i in l1:
  print(i)

  print(l1[i:i+2])

2
[6, 4]
5
[9, 8]
6
[8, 12]
4
[7, 9]
7
[12]
9
[]
8
[]
12
[]


In [ ]:
# continuing the workflow from the video:

print(xb) # our input to the transformer

tensor([[57,  1, 46, 47, 57,  1, 50, 53],
        [ 1, 58, 46, 43, 56, 43,  1, 41],
        [17, 26, 15, 17, 10,  0, 32, 53],
        [57, 58,  6,  1, 61, 47, 58, 46]])


In [ ]:
# Building model class
import torch
import torch.nn as nn
from torch.nn import functional as F

torch.manual_seed(1337)

class BigramLanguageModel(nn.Module):

  def __init__(self, vocab_size):
    super().__init__()

    # each token directly reads off the logits for the next token from a look up table
    self.token_embedding_table = nn.Embedding(vocab_size, vocab_size)
    print(f'{self.token_embedding_table} \n')

  def forward(self, idx, targets = None):

    # idx and targets both are (B, T) tensor of integers
    logits = self.token_embedding_table(idx) # (B, T, C)

    if targets is None:
      loss = None

    else:
      B, T, C = logits.shape
      print(f'Batch is: {B}, Time is: {T}, Channel is: {C} \n')
      logits = logits.view(B*T, C)
      print(f'logits: {logits} and \n logits shape is: {logits.shape}')

      targets = targets.view(B*T)
      print(f'Targets: {targets}')
      loss = F.cross_entropy(logits, targets)

    return logits, loss

  def generate(self, idx, max_new_token):

    # idx is (B, T) array of indices in the current context
    for _ in range(max_new_token):

      # get the predictions
      logits, loss = self(idx)

      # focus only on the last time step
      logits = logits[:, -1, :] # becomes (B, C)
      #print(f"logits shape is: {logits.shape}")

      # apply softmax to get probabilities
      probs = torch.softmax(logits, dim = 1) # (B, C)
      #print(f'probs shape is: {probs.shape}')

      # sample from the distribution
      idx_next = torch.multinomial(probs, num_samples = 1) # (b, 1)
      #print(f'idx_next shape is: {idx_next.shape}')

      # append sample index to the running sequence
      idx = torch.cat((idx, idx_next), dim = 1) # (B, T+1)
      #print(f'idx: {idx} shape is: {idx.shape}')

    return idx

In [ ]:
m = BigramLanguageModel(vocab_size)
logits, loss = m(xb, yb)
# print(logits.shape)
print(f'loss is => {loss}')

idx = torch.zeros((1, 1), dtype = torch.long)
#print(idx)
print(decode(m.generate(idx, max_new_token = 100)[0].tolist()))

Embedding(65, 65) 

Batch is: 4, Time is: 8, Channel is: 65 

logits: tensor([[-0.5201,  0.2831,  1.0847,  ..., -0.0198,  0.7959,  1.6014],
        [ 0.5978, -0.0514, -0.0646,  ..., -1.4649, -2.0555,  1.8275],
        [ 1.0901,  0.2170, -2.9996,  ..., -0.5472, -0.8017,  0.7761],
        ...,
        [ 1.6515, -0.0424, -0.7355,  ...,  0.8682,  2.0593, -0.8159],
        [ 0.2475, -0.6349, -1.2909,  ...,  1.3064, -0.2256, -1.8305],
        [ 1.0901,  0.2170, -2.9996,  ..., -0.5472, -0.8017,  0.7761]],
       grad_fn=<ViewBackward0>) and 
 logits shape is: torch.Size([32, 65])
Targets: tensor([ 1, 46, 47, 57,  1, 50, 53, 60, 58, 46, 43, 56, 43,  1, 41, 39, 26, 15,
        17, 10,  0, 32, 53,  1, 58,  6,  1, 61, 47, 58, 46,  0])
loss is => 4.701268196105957

SKIcLT;AcELMoTbvZv C?nq-QE33:CJqkOKH-q;:la!oiywkHjgChzbQ?u!3bLIgwevmyFJGUGp
wnYWmnxKWWev-tDqXErVKLgJ


In [ ]:
import torch

embedding = torch.nn.Embedding(3, 4)

print(f'embedding weights are: {embedding.weight} \n')

print(embedding(torch.tensor([0]))) # printing a tensor which is ideal to 0th row of embedding table

embedding weights are: Parameter containing:
tensor([[-0.3588,  0.6541, -1.3501, -1.0958],
        [-0.3938, -0.6300,  1.0083, -1.1603],
        [-0.5546,  0.0533, -2.0236,  0.2138]], requires_grad=True) 

tensor([[-0.3588,  0.6541, -1.3501, -1.0958]], grad_fn=<EmbeddingBackward0>)


In [ ]:
import torch

tensor_1 = torch.rand(3, 4)
tensor_1

tensor([[0.5733, 0.4173, 0.0410, 0.1195],
        [0.0350, 0.7011, 0.9785, 0.2568],
        [0.6487, 0.9395, 0.4513, 0.5866]])

In [ ]:
result_1 = torch.multinomial(tensor_1, num_samples = 3)
result_1

tensor([[0, 1, 3],
        [1, 2, 0],
        [1, 2, 0]])

In [ ]:
tensor_2 = torch.rand(3, 4)
tensor_2

tensor([[0.4695, 0.3617, 0.8061, 0.4760],
        [0.4524, 0.6071, 0.2800, 0.9597],
        [0.6697, 0.1488, 0.2350, 0.3079]])

In [ ]:
result_2 = torch.multinomial(tensor_2, num_samples = 1)
result_2

tensor([[2],
        [3],
        [0]])

In [ ]:
result_2.shape

torch.Size([3, 1])

In [ ]:
# create an optimizer
optimizer = torch.optim.AdamW(m.parameters(), lr = 0.001, weight_decay = True)
optimizer

AdamW (
Parameter Group 0
    amsgrad: False
    betas: (0.9, 0.999)
    capturable: False
    decoupled_weight_decay: True
    differentiable: False
    eps: 1e-08
    foreach: None
    fused: None
    lr: 0.001
    maximize: False
    weight_decay: True
)

In [ ]:
batch_size = 32

for steps in range(10000):

  # sample a batch of data
  xb, xa = get_batch('train')

  # evaluate the loss
  optimizer.zero_grad()
  logits, loss = m(xa, xb)
  loss.backward()
  optimizer.step()

print(loss.item())

Streaming output truncated to the last 5000 lines.
        15, 21, 26, 21, 33, 31, 53, 51, 39, 57,  1, 25, 53, 61, 43,  1, 46, 39,
        57, 58, 43,  6])
Batch is: 32, Time is: 8, Channel is: 65 

logits: tensor([[ 0.4858,  0.2861, -0.6503,  ..., -0.6318, -0.6454, -0.6412],
        [ 0.1789,  0.2616, -0.7133,  ..., -0.7340, -0.7239, -0.7328],
        [ 0.3676,  0.0044, -0.6859,  ..., -0.6962, -0.7068, -0.6922],
        ...,
        [ 0.7089, -0.9389,  0.0805,  ..., -0.8847, -0.2820, -0.9634],
        [ 0.7089, -0.9389,  0.0805,  ..., -0.8847, -0.2820, -0.9634],
        [ 0.4166,  0.2711, -0.6811,  ..., -0.6921, -0.6923, -0.6837]],
       grad_fn=<ViewBackward0>) and 
 logits shape is: torch.Size([256, 65])
Targets: tensor([ 0, 20, 17, 26, 30, 37,  1, 14,  1, 57, 43, 52, 39, 58, 53, 56, 23, 10,
         0, 26, 53, 61,  6,  1, 34, 10,  0, 35, 46, 39, 58,  6, 40, 53, 59, 58,
         6,  1, 39, 52,  1, 61, 46, 43, 52, 41, 43,  1, 57, 43,  6,  1, 47, 44,
         1, 47, 47, 53, 52,  1, 5

In [ ]:
idx = torch.zeros((1,1), dtype = torch.long)
print(decode(m.generate(idx, max_new_token = 500)[0].tolist()))


!3JMps
riIY far;x;woSxjNelBCqvLOjAv fl;SP.waYZGbD s hhW;IUQYd F3lS
lug3&XpMIvLvP chxGib,!JVvGLR;A3xDy:kXu
tblsewyroPjPclotlKU$'rm?&?kKOJF-?Gzi-QCgL3uROD3?fI?Tqndo orPwgohfWPem ZH$:MzBaob m:gtCoSSjqsaJHU!ZVUJtDUhiO-V?TjFP$DAW;wXd!EWvwyg ,uj;gav&Qj:aEZ'rwpGG.P lahPUVHx3Ow'TUrZTdrAzt eN,hN,PrXQ3H;ste'gpFT!pP;?OGdxpCNLvgriJ&meha:T?;pB?DwHlRF nJZNSPEGSARPJlm hcS$t3JpdJnEPDoGb HX3;.uvv ,txE-nja ?ehWVmajQlanpHA&vx$ofoti Jz-Q;LgPetldfztDlamB!k EaxiVwjXfejQBPI y j
sddo 3zul?elZcfiZciPV,PhgOvIpT'er&kudASW


In [ ]:
# consider the following toy example:
import torch
torch.manual_seed(42)
B,T,C = 4, 8, 2 # batch, time, channel
x = torch.randn(B,T,C)
x, x.shape

(tensor([[[ 1.9269,  1.4873],
          [ 0.9007, -2.1055],
          [ 0.6784, -1.2345],
          [-0.0431, -1.6047],
          [-0.7521,  1.6487],
          [-0.3925, -1.4036],
          [-0.7279, -0.5594],
          [-0.7688,  0.7624]],
 
         [[ 1.6423, -0.1596],
          [-0.4974,  0.4396],
          [-0.7581,  1.0783],
          [ 0.8008,  1.6806],
          [ 1.2791,  1.2964],
          [ 0.6105,  1.3347],
          [-0.2316,  0.0418],
          [-0.2516,  0.8599]],
 
         [[-1.3847, -0.8712],
          [-0.2234,  1.7174],
          [ 0.3189, -0.4245],
          [ 0.3057, -0.7746],
          [-1.5576,  0.9956],
          [-0.8798, -0.6011],
          [-1.2742,  2.1228],
          [-1.2347, -0.4879]],
 
         [[-0.9138, -0.6581],
          [ 0.0780,  0.5258],
          [-0.4880,  1.1914],
          [-0.8140, -0.7360],
          [-1.4032,  0.0360],
          [-0.0635,  0.6756],
          [-0.0978,  1.8446],
          [-1.1845,  1.3835]]]),
 torch.Size([4, 8, 2]))

In [ ]:
# trying to build our own attension
# we want x[b, t] = mean_{i<=t} x[b, 1]
x_bag_of_words = torch.zeros((B, T, C)) # with or without extra braces, the dim is same
for b in range(B):
  for t in range(T):
    x_prev = x[b,:t+1] # [T, C]
    x_bag_of_words[b, t] = torch.mean(x_prev, 0)

In [ ]:
x[0]

tensor([[ 1.9269,  1.4873],
        [ 0.9007, -2.1055],
        [ 0.6784, -1.2345],
        [-0.0431, -1.6047],
        [-0.7521,  1.6487],
        [-0.3925, -1.4036],
        [-0.7279, -0.5594],
        [-0.7688,  0.7624]])

In [ ]:
x_bag_of_words[0]

tensor([[ 1.9269,  1.4873],
        [ 1.4138, -0.3091],
        [ 1.1687, -0.6176],
        [ 0.8657, -0.8644],
        [ 0.5422, -0.3617],
        [ 0.3864, -0.5354],
        [ 0.2272, -0.5388],
        [ 0.1027, -0.3762]])

In [ ]:
torch.tril(torch.ones(3,3))

tensor([[1., 0., 0.],
        [1., 1., 0.],
        [1., 1., 1.]])

In [ ]:
torch.manual_seed(42)
a = torch.tril(torch.ones(3, 3))
a = a / torch.sum(a, dim = 1, keepdim=True)
b = torch.randint(0, 10, (3,2), dtype = torch.float)
c = a @ b
print(f'a= {a}')
print('---')
print(f'b= {b} ')
print('---')
print(f'c= {c}')


a= tensor([[1.0000, 0.0000, 0.0000],
        [0.5000, 0.5000, 0.0000],
        [0.3333, 0.3333, 0.3333]])
---
b= tensor([[2., 7.],
        [6., 4.],
        [6., 5.]]) 
---
c= tensor([[2.0000, 7.0000],
        [4.0000, 5.5000],
        [4.6667, 5.3333]])


In [ ]:
sum = torch.sum(a, dim = 1, keepdim=True)
sum

tensor([[1.],
        [1.],
        [1.]])

In [ ]:
sum2 = a[2] / sum[2]
sum2
# broadcasting happens so each 3 divides 1 resulting into a 0.333

tensor([0.3333, 0.3333, 0.3333])

In [ ]:
# continuing with video
weights = torch.tril(torch.ones(T, T))
weights = weights / weights.sum(dim = 1, keepdim = True)
weights # -> each row sum to 1.0

tensor([[1.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.5000, 0.5000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.3333, 0.3333, 0.3333, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.2500, 0.2500, 0.2500, 0.2500, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.2000, 0.2000, 0.2000, 0.2000, 0.2000, 0.0000, 0.0000, 0.0000],
        [0.1667, 0.1667, 0.1667, 0.1667, 0.1667, 0.1667, 0.0000, 0.0000],
        [0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.0000],
        [0.1250, 0.1250, 0.1250, 0.1250, 0.1250, 0.1250, 0.1250, 0.1250]])

In [ ]:
x_bag_of_words_2 = weights @ x # ---> (B, T, T) @ (B, T, C) => (B, T, C)
# weights will automaitcally get one more dim as B to match the matmul
x_bag_of_words_2

tensor([[[ 1.9269,  1.4873],
         [ 1.4138, -0.3091],
         [ 1.1687, -0.6176],
         [ 0.8657, -0.8644],
         [ 0.5422, -0.3617],
         [ 0.3864, -0.5354],
         [ 0.2272, -0.5388],
         [ 0.1027, -0.3762]],

        [[ 1.6423, -0.1596],
         [ 0.5725,  0.1400],
         [ 0.1289,  0.4528],
         [ 0.2969,  0.7597],
         [ 0.4933,  0.8671],
         [ 0.5129,  0.9450],
         [ 0.4065,  0.8160],
         [ 0.3242,  0.8215]],

        [[-1.3847, -0.8712],
         [-0.8040,  0.4231],
         [-0.4297,  0.1405],
         [-0.2459, -0.0882],
         [-0.5082,  0.1285],
         [-0.5701,  0.0069],
         [-0.6707,  0.3092],
         [-0.7412,  0.2095]],

        [[-0.9138, -0.6581],
         [-0.4179, -0.0662],
         [-0.4413,  0.3530],
         [-0.5344,  0.0808],
         [-0.7082,  0.0718],
         [-0.6008,  0.1724],
         [-0.5289,  0.4113],
         [-0.6109,  0.5329]]])

In [ ]:
weights.shape, x.shape

(torch.Size([8, 8]), torch.Size([4, 8, 2]))

In [ ]:
# check if x_bag_of_words and x_bag_of_words_2 are identical
torch.allclose(x_bag_of_words, x_bag_of_words_2)

True

In [ ]:
# self-attension!

torch.manual_seed(1337)
B, T, C = 4, 8, 32 # (batch, time, channels)
x = torch.randn(B, T, C)

# let's see a single head perform self-attension
head_size = 16
key = nn.Linear(C, head_size, bias = False)
query = nn.Linear(C, head_size, bias = False)
value = nn.Linear(C, head_size, bias = False)

k = key(x)  # (B, T, 16)
q = query(x) # (B, T, 16)
wei = q @ k.transpose(-2, -1) # (B, T, 16) @ (B, 16, T) ---> (B, T, T)

tril = torch.tril(torch.ones(T, T))
# wei = torch.zeros((T, T))
wei = wei.masked_fill(tril == 0, float('-inf'))
# print(wei)
wei = torch.softmax(wei, dim = -1)

v = value(x)
out = wei @ v

# out = wei @ x

out.shape

torch.Size([4, 8, 16])

In [ ]:
wei[0]

tensor([[1.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.1574, 0.8426, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.2088, 0.1646, 0.6266, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.5792, 0.1187, 0.1889, 0.1131, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.0294, 0.1052, 0.0469, 0.0276, 0.7909, 0.0000, 0.0000, 0.0000],
        [0.0176, 0.2689, 0.0215, 0.0089, 0.6812, 0.0019, 0.0000, 0.0000],
        [0.1691, 0.4066, 0.0438, 0.0416, 0.1048, 0.2012, 0.0329, 0.0000],
        [0.0210, 0.0843, 0.0555, 0.2297, 0.0573, 0.0709, 0.2423, 0.2391]],
       grad_fn=<SelectBackward0>)

In [ ]:
for _ in 'Hello World':
  print(_)

H
e
l
l
o
 
W
o
r
l
d


In [ ]:
x, _, y = (1, 2, 3)
print(x, y)

1 3


In [ ]:
import torch
from torch import nn

L1 = nn.Linear(in_features=3, out_features=5, bias = False)
L2 = nn.Linear(in_features=5, out_features=1, bias = False)
print(L1.weight)
print(L2.weight)

Parameter containing:
tensor([[-0.4336, -0.0416, -0.0212],
        [ 0.4281, -0.4159,  0.1278],
        [-0.1408,  0.0934, -0.2744],
        [ 0.4940,  0.0129, -0.4911],
        [ 0.2790, -0.1723,  0.5097]], requires_grad=True)
Parameter containing:
tensor([[-0.0755, -0.0953, -0.3364, -0.0634, -0.4222]], requires_grad=True)




---



## Section 1 - Hyperparameters

In [ ]:
import torch
from torch import nn
from torch.nn import functional as F

In [ ]:
# 1. Set a random seed for reproducibility
torch.manual_seed(42)

# 2. Set batch size to 64
batch_size = 64 # -> how many sequences to process in parallel. Bigger the batch size, faster training but more memory

# 3. Set block size (context length) to 256
block_size = 256 # -> The maximum context length i.e. how many previous tokens the model can look at when predicting next token

# 4. Set max training iterations to 5000
# max_iterations = 5000 # -> total training steps
max_iterations = 10
# 5. Set how often to evaluate
eval_interval = 5 # -> Every 500 steps, print how well the model is doing on train and val test.

# 6. Set learning rate
lr = 0.0003 # -> How big each weight update step is. Bigger steps = unstable, smaller steps = too slow learning

# 7. Make device agnostic
device = 'cuda' if torch.cuda.is_available() else 'cpu'

# 8. Set how many batches to use when estimating loss
eval_iterations = 2 # -> When evaluating, average loss over 200 batches to get a stable estimate instead of one noisy batch.

# 9. Set embedding size
embedding_size = 384 # -> how many numbers represent each token. This is C.

# 10. Set number of attention heads
num_attention_heads = 6 # -> How many attention heads in each transformer block. - multiple heads having different roles
# like recognizing the vowels, occurence, grammar etc

# 11. Set number of transformer layers
num_tranformer_layers = 6 # -> How many transformer blocks stacked on top of each other. - How many layers we want for the input to output phase

# 12. Set dropout
drop_out = 0.2 # -> Randomly zero out 20% of neurons during training to prevent overfitting.

## Section 2 — Data loading and tokenizer

What we're doing: reading the raw text, building a character-level vocabulary, creating encode/decode functions, converting the full text to integers, and splitting into train and val.

In [ ]:
# reading the raw text
!wget https://raw.githubusercontent.com/karpathy/char-rnn/master/data/tinyshakespeare/input.txt
with open('input.txt', 'r') as f:
  text = f.read()

--2026-06-04 19:47:16--  https://raw.githubusercontent.com/karpathy/char-rnn/master/data/tinyshakespeare/input.txt
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1115394 (1.1M) [text/plain]
Saving to: ‘input.txt.2’

input.txt.2         100%[===================>]   1.06M  --.-KB/s    in 0.01s   

2026-06-04 19:47:16 (73.6 MB/s) - ‘input.txt.2’ saved [1115394/1115394]



In [ ]:
len(text)

1115394

In [ ]:
text[:1000]

"First Citizen:\nBefore we proceed any further, hear me speak.\n\nAll:\nSpeak, speak.\n\nFirst Citizen:\nYou are all resolved rather to die than to famish?\n\nAll:\nResolved. resolved.\n\nFirst Citizen:\nFirst, you know Caius Marcius is chief enemy to the people.\n\nAll:\nWe know't, we know't.\n\nFirst Citizen:\nLet us kill him, and we'll have corn at our own price.\nIs't a verdict?\n\nAll:\nNo more talking on't; let it be done: away, away!\n\nSecond Citizen:\nOne word, good citizens.\n\nFirst Citizen:\nWe are accounted poor citizens, the patricians good.\nWhat authority surfeits on would relieve us: if they\nwould yield us but the superfluity, while it were\nwholesome, we might guess they relieved us humanely;\nbut they think we are too dear: the leanness that\nafflicts us, the object of our misery, is as an\ninventory to particularise their abundance; our\nsufferance is a gain to them Let us revenge this with\nour pikes, ere we become rakes: for the gods know I\nspeak this in hunger 

In [ ]:
# building a character-level vocabulary
chars = sorted(set(list(text)))
chars

['\n',
 ' ',
 '!',
 '$',
 '&',
 "'",
 ',',
 '-',
 '.',
 '3',
 ':',
 ';',
 '?',
 'A',
 'B',
 'C',
 'D',
 'E',
 'F',
 'G',
 'H',
 'I',
 'J',
 'K',
 'L',
 'M',
 'N',
 'O',
 'P',
 'Q',
 'R',
 'S',
 'T',
 'U',
 'V',
 'W',
 'X',
 'Y',
 'Z',
 'a',
 'b',
 'c',
 'd',
 'e',
 'f',
 'g',
 'h',
 'i',
 'j',
 'k',
 'l',
 'm',
 'n',
 'o',
 'p',
 'q',
 'r',
 's',
 't',
 'u',
 'v',
 'w',
 'x',
 'y',
 'z']

In [ ]:
len(chars)

65

In [ ]:
print(''.join(chars))
vocab_len = len(chars)
vocab_len


 !$&',-.3:;?ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz


65

In [ ]:
vocab_len

65

In [ ]:
str_to_int = {ch:i for i, ch in enumerate(chars)}
str_to_int

{'\n': 0,
 ' ': 1,
 '!': 2,
 '$': 3,
 '&': 4,
 "'": 5,
 ',': 6,
 '-': 7,
 '.': 8,
 '3': 9,
 ':': 10,
 ';': 11,
 '?': 12,
 'A': 13,
 'B': 14,
 'C': 15,
 'D': 16,
 'E': 17,
 'F': 18,
 'G': 19,
 'H': 20,
 'I': 21,
 'J': 22,
 'K': 23,
 'L': 24,
 'M': 25,
 'N': 26,
 'O': 27,
 'P': 28,
 'Q': 29,
 'R': 30,
 'S': 31,
 'T': 32,
 'U': 33,
 'V': 34,
 'W': 35,
 'X': 36,
 'Y': 37,
 'Z': 38,
 'a': 39,
 'b': 40,
 'c': 41,
 'd': 42,
 'e': 43,
 'f': 44,
 'g': 45,
 'h': 46,
 'i': 47,
 'j': 48,
 'k': 49,
 'l': 50,
 'm': 51,
 'n': 52,
 'o': 53,
 'p': 54,
 'q': 55,
 'r': 56,
 's': 57,
 't': 58,
 'u': 59,
 'v': 60,
 'w': 61,
 'x': 62,
 'y': 63,
 'z': 64}

In [ ]:
int_to_str = {i:ch for i, ch in enumerate(chars)}
int_to_str

{0: '\n',
 1: ' ',
 2: '!',
 3: '$',
 4: '&',
 5: "'",
 6: ',',
 7: '-',
 8: '.',
 9: '3',
 10: ':',
 11: ';',
 12: '?',
 13: 'A',
 14: 'B',
 15: 'C',
 16: 'D',
 17: 'E',
 18: 'F',
 19: 'G',
 20: 'H',
 21: 'I',
 22: 'J',
 23: 'K',
 24: 'L',
 25: 'M',
 26: 'N',
 27: 'O',
 28: 'P',
 29: 'Q',
 30: 'R',
 31: 'S',
 32: 'T',
 33: 'U',
 34: 'V',
 35: 'W',
 36: 'X',
 37: 'Y',
 38: 'Z',
 39: 'a',
 40: 'b',
 41: 'c',
 42: 'd',
 43: 'e',
 44: 'f',
 45: 'g',
 46: 'h',
 47: 'i',
 48: 'j',
 49: 'k',
 50: 'l',
 51: 'm',
 52: 'n',
 53: 'o',
 54: 'p',
 55: 'q',
 56: 'r',
 57: 's',
 58: 't',
 59: 'u',
 60: 'v',
 61: 'w',
 62: 'x',
 63: 'y',
 64: 'z'}

In [ ]:
# creating encode/decode functions
str_encoder = lambda string : [str_to_int[c] for c in string]
str_encoder

<function __main__.<lambda>(string)>

In [ ]:
str_encoder('hello')

[46, 43, 50, 50, 53]

In [ ]:
str_decoder = lambda integer : ''.join([int_to_str[c] for c in integer]) # without join we would get ['h','e','l','l','o]
str_decoder

<function __main__.<lambda>(integer)>

In [ ]:
type(int_to_str)

dict

In [ ]:
str_decoder([46, 43, 50, 50, 53])

'hello'

In [ ]:
print(str_encoder(text[:100]))

[18, 47, 56, 57, 58, 1, 15, 47, 58, 47, 64, 43, 52, 10, 0, 14, 43, 44, 53, 56, 43, 1, 61, 43, 1, 54, 56, 53, 41, 43, 43, 42, 1, 39, 52, 63, 1, 44, 59, 56, 58, 46, 43, 56, 6, 1, 46, 43, 39, 56, 1, 51, 43, 1, 57, 54, 43, 39, 49, 8, 0, 0, 13, 50, 50, 10, 0, 31, 54, 43, 39, 49, 6, 1, 57, 54, 43, 39, 49, 8, 0, 0, 18, 47, 56, 57, 58, 1, 15, 47, 58, 47, 64, 43, 52, 10, 0, 37, 53, 59]


In [ ]:
print(str_decoder(str_encoder(text[:100])))

First Citizen:
Before we proceed any further, hear me speak.

All:
Speak, speak.

First Citizen:
You


In [ ]:
# currently we have the encoder decoder of list type
result = str_encoder(text[:100])
type(result)

list

In [ ]:
# we need to convert these to tensors for our NN model compatibility
import torch

tensor_data = torch.tensor(str_encoder(text), dtype = torch.long)
print(f'The list type to tensor type data: {tensor_data} \nand its shape: {tensor_data.shape}')

The list type to tensor type data: tensor([18, 47, 56,  ..., 45,  8,  0]) 
and its shape: torch.Size([1115394])


In [ ]:
print(tensor_data[:100])

tensor([18, 47, 56, 57, 58,  1, 15, 47, 58, 47, 64, 43, 52, 10,  0, 14, 43, 44,
        53, 56, 43,  1, 61, 43,  1, 54, 56, 53, 41, 43, 43, 42,  1, 39, 52, 63,
         1, 44, 59, 56, 58, 46, 43, 56,  6,  1, 46, 43, 39, 56,  1, 51, 43,  1,
        57, 54, 43, 39, 49,  8,  0,  0, 13, 50, 50, 10,  0, 31, 54, 43, 39, 49,
         6,  1, 57, 54, 43, 39, 49,  8,  0,  0, 18, 47, 56, 57, 58,  1, 15, 47,
        58, 47, 64, 43, 52, 10,  0, 37, 53, 59])


In [ ]:
# split the data into train and val

total_length_of_text = len(tensor_data)
print(total_length_of_text)

size = 0.9 * total_length_of_text

train_data = tensor_data[:int(size)]
val_data = tensor_data[int(size):]
print(train_data.shape, val_data.shape)

1115394
torch.Size([1003854]) torch.Size([111540])


## Section 3 — get_batch

get_batch — purpose:

During training, we can't feed the entire dataset at once — too much memory.
So every training step, we randomly grab a small chunk.

Why random? So the model sees different parts of the text every step.
If we always fed the same sequences in the same order, the model would
memorize the order rather than learning the language patterns.

What it returns:
- x: batch_size sequences of block_size token IDs  → the input
- y: same but shifted by 1                          → the target

Shape:
- x: (batch_size, block_size) = (4, 8) = 32 token IDs
- y: (batch_size, block_size) = (4, 8) = 32 targets

At this point just integers. Embeddings happen inside the model.
Device transfer ensures data and model are in the same place.

Every training step calls get_batch → gets a fresh random batch →
model learns from it → weights update → repeat.

In [ ]:
batch_size = 4 # -> how many time context lengths to proceed in one go

block_size = 8 # -> context length - how many tokens we want to process in one go

def get_batch(split: str):

  data = train_data if split == 'train' else val_data

  dataset = torch.randint(len(data) - block_size, (batch_size,))
  print(f'{dataset} shape of the dataset for x and y: {dataset.shape}\n')

  x = torch.stack([data[i : i + block_size] for i in dataset])
  print(f'sample {x} and the shape: {x.shape}\n')

  y = torch.stack([data[i + 1 : i + block_size + 1] for i in dataset])
  print(f'sample {y} and the shape: {y.shape}\n')

  for k in dataset:
    print(f'when k = {k}: \n')
    xx = data[k : k + block_size]
    yy = data[k + 1 : k +block_size + 1]
    print(xx)
    print("\n")
    print(yy)

    """The print statement is to showcase that the "dataset" has 4 elements in it size we gave the
    1D batch_size as a size and the elements are within the range of 0 to len(data) - block_size.as_integer_ratio

    The next prints for x and y and the following loop is to:
      - At this stage x and y are just token IDs — plain integers. No weightages yet. The embedding lookup hasn't happened yet. That happens inside the model.
        So x is just:
        [[3, 2, 4, 4, 5, 0, 7, 5],   ← 8 token IDs for sequence 1
        [6, 4, 1, 2, 3, 5, 2, 4],   ← 8 token IDs for sequence 2
        ...
    Just integers. The embedding vectors come later when these IDs are passed through the model.
  """
  x, y = x.to(device), y.to(device)

  return x, y

In [ ]:
temp = get_batch('train')

tensor([476250,  18899, 645194, 831150]) shape of the dataset for x and y: torch.Size([4])

sample tensor([[57,  1, 46, 47, 57,  1, 50, 53],
        [ 1, 58, 46, 43, 56, 43,  1, 41],
        [17, 26, 15, 17, 10,  0, 32, 53],
        [57, 58,  6,  1, 61, 47, 58, 46]]) and the shape: torch.Size([4, 8])

sample tensor([[ 1, 46, 47, 57,  1, 50, 53, 60],
        [58, 46, 43, 56, 43,  1, 41, 39],
        [26, 15, 17, 10,  0, 32, 53,  1],
        [58,  6,  1, 61, 47, 58, 46,  0]]) and the shape: torch.Size([4, 8])

when k = 476250: 

tensor([57,  1, 46, 47, 57,  1, 50, 53])


tensor([ 1, 46, 47, 57,  1, 50, 53, 60])
when k = 18899: 

tensor([ 1, 58, 46, 43, 56, 43,  1, 41])


tensor([58, 46, 43, 56, 43,  1, 41, 39])
when k = 645194: 

tensor([17, 26, 15, 17, 10,  0, 32, 53])


tensor([26, 15, 17, 10,  0, 32, 53,  1])
when k = 831150: 

tensor([57, 58,  6,  1, 61, 47, 58, 46])


tensor([58,  6,  1, 61, 47, 58, 46,  0])


## Section 4 — estimate_loss

What: A function that measures how well the model is currently performing on both train and val data.
Why: The training loop updates weights every step. But the loss from one single batch is noisy, it fluctuates a lot. To get a stable picture of how the model is actually doing, we average the loss over many batches.

In [ ]:
a = torch.zeros(5)
a # -> 1d of 5 zeros not 5x5 zeros

tensor([0., 0., 0., 0., 0.])

In [ ]:
@torch.inference_mode()
def estimate_loss():

  # an empty dictionary to store the losses for both train and val splits
  results = {}

  # put the model in eval mode
  model.eval()

  for split in ['train', 'val']:

    # Create a tensor to store losses for each batch
    store_losses = torch.zeros(eval_iterations) # eval_iterations size of zeros

    for k in range(eval_iterations):

      X, Y = get_batch(split) # get the current character and target character

      logits, loss = model(X, Y) # unpack the logits and loss from the model training

      store_losses[k] = loss.item() # store the plain python loss

    results[split] = store_losses.mean() # avg the store losses per splits

  model.train() # put the model in training mode

  return results


## Section 5 - Head — single attention head

In [ ]:
class Head(nn.Module):

  def __init__(self, head_size):

    super().__init__()

    self.weighted_key = nn.Linear(embedding_size, head_size, bias = False)
    print(self.weighted_key,'\n')
    self.weighted_query = nn.Linear(embedding_size, head_size, bias = False)
    print(self.weighted_query,'\n')
    self.weighted_value = nn.Linear(embedding_size, head_size, bias = False)
    print(self.weighted_value,'\n')

    self.register_buffer('tril', torch.tril(torch.ones(block_size, block_size)))
    print(self.register_buffer,'\n')
    # -> Purpose is to block future tokens. We store the triangular of ones as a buffer and not a learnable params, just
    # a fixed matrix that moves to GPU with the model
    # torch.ones(...) -> creates a matrix of all 1s.
    # torch.trils(...) -> keeps only the lower triangle, uppers are the zeros
    # register_buffer -> stores it as part of the model without make it learnable.

    self.dropout = nn.Dropout(drop_out)
    # -> randomly zero out some attention weights during training to prevent overfitting


  def forward(self, x):

    B, T, C = x.shape
    print(f'original x shape: {x.shape} unpacked to B, T, C: {B, T, C}\n')
    K = self.weighted_key(x) # x (B, T, C) @ Wk (C, head_size) → K (B, T, head_size)
    Q = self.weighted_query(x) # x (B, T, C) @ Wq (C, head_size) → Q (B, T, head_size)
    V = self.weighted_value(x) # x (B, T, C) @ Wv (C, head_size) → V (B, T, head_size)

    scores = Q @ K.transpose(-2, -1) / K.shape[-1]**-0.5
    # -> -2 and -1 refer to the last two dimensions:
    # k shape: (B, T, head_size)
    #           0   -2    -1    -> swaps T and head_size -> (B, head_size, T)
    # (B, T, head_size) @ (B, head_size, T) -> (B, T, T)

    scores = scores.masked_fill(self.tril[:T, :T] == 0, float('-inf')) # -> slice the triangle to
    # current sequence length T and then == 0 is to find the upper triangle positions. the masked_fill
    # replaces those 0s with -inf
    print(f'Current scores: {scores} \n')

    scores = torch.softmax(scores, dim = -1) # -> convert and sums the weight to 1 per row. dim = -1 means
    # softmax along the last dimension, each row independently

    scores = self.dropout(scores) # -> randomly 0s some attention during training.
    output = scores @ V # (B,T,T) @ (B,T,head_size) -> (B,T,head_size)
    print(f'Output at this point: {output} \n')

    return output

## Section 6 - MultiHeadAttention

In [ ]:
class MultiHeadAttention(nn.Module):

  def __init__(self, num_heads, head_size):

    super().__init__()

    self.heads = nn.ModuleList([Head(head_size) for _ in range(num_heads)])

    self.back_to_original_size = nn.Linear(head_size * num_heads, embedding_size)

    self.dropout = nn.Dropout(drop_out)

  def forward(self, x):

    output = torch.cat([h(x) for h in self.heads], dim=-1)
    print(f'after concatenation: {output} \n')

    projection = self.back_to_original_size(output)
    print(f'projection: {projection} \n')

    drop_out = self.dropout(projection)

    return drop_out

In [ ]:
class FeedForward(nn.Module):

  def __init__(self, embedding_size):

    super().__init__()

    self.layer = nn.Sequential(
        nn.Linear(embedding_size, 4 * embedding_size),
        nn.ReLU(),
        nn.Linear(4 * embedding_size, embedding_size),
        nn.Dropout(drop_out)
    )

  def forward(self, x):
    return self.layer(x)


## Section 8 — Block

In [ ]:
class Block(nn.Module):

  def __init__(self, embedding_size, num_heads):

    super().__init__()

    self.mha = MultiHeadAttention(num_heads, embedding_size // num_heads)
    print(f'Self Attention: {self.mha} \n')
    self.ffwd = FeedForward(embedding_size)
    self.ln1 = nn.LayerNorm(embedding_size)
    self.ln2 = nn.LayerNorm(embedding_size)

  def forward(self,x):
    x = x + self.mha(self.ln1(x))
    x = x + self.ffwd(self.ln2(x))

    return x

In [ ]:
class GPTLanguageModel(nn.Module):

  def __init__(self):

    super().__init__()

    self.token_embedding_table = nn.Embedding(vocab_len, embedding_size)
    print(f'token embedding table: {self.token_embedding_table}\n')
    self.positional_embedding_table = nn.Embedding(block_size, embedding_size)
    print(f'positional embedding table: {self.positional_embedding_table}\n')
    self.blocks = nn.Sequential(*[Block(embedding_size, num_heads = num_attention_heads) for _ in range(num_tranformer_layers)])
    self.ln_f = nn.LayerNorm(embedding_size) # final layer norm
    self.lm_head = nn.Linear(embedding_size, vocab_len)

  def forward(self, idx, targets=None):

    B, T = idx.shape

    # idx and targets are both (B,T) tensor of integers
    tok_emb = self.token_embedding_table(idx) # (B,T,C)
    pos_emb = self.positional_embedding_table(torch.arange(T, device=device)) # (T,C)
    x = tok_emb + pos_emb # (B,T,C)
    x = self.blocks(x) # (B,T,C)
    x = self.ln_f(x) # (B,T,C)
    logits = self.lm_head(x) # (B,T,vocab_size)

    if targets is None:
        loss = None
    else:
        B, T, C = logits.shape
        logits = logits.view(B*T, C)
        targets = targets.view(B*T)
        loss = F.cross_entropy(logits, targets)

    return logits, loss


  def generate(self, idx, max_new_tokens):
    # idx is (B, T) array of indices in the current context
    for _ in range(max_new_tokens):
        # crop idx to the last block_size tokens
        idx_cond = idx[:, -block_size:]
        # get the predictions
        logits, loss = self(idx_cond)
        # focus only on the last time step
        logits = logits[:, -1, :] # becomes (B, C)
        # apply softmax to get probabilities
        probs = F.softmax(logits, dim=-1) # (B, C)
        # sample from the distribution
        idx_next = torch.multinomial(probs, num_samples=1) # (B, 1)
        # append sampled index to the running sequence
        idx = torch.cat((idx, idx_next), dim=1) # (B, T+1)
    return idx


In [ ]:
model = GPTLanguageModel()
m = model.to(device)
# print the number of parameters in the model
print(sum(p.numel() for p in m.parameters())/1e6, 'M parameters')

# create a PyTorch optimizer
optimizer = torch.optim.AdamW(model.parameters(), lr=lr)

for iter in range(max_iterations):

    # every once in a while evaluate the loss on train and val sets
    if iter % eval_interval == 0 or iter == max_iterations - 1:
        losses = estimate_loss()
        print(f"step {iter}: train loss {losses['train']:.4f}, val loss {losses['val']:.4f}")

    # sample a batch of data
    xb, yb = get_batch('train')

    # evaluate the loss
    logits, loss = model(xb, yb)
    optimizer.zero_grad(set_to_none=True)
    loss.backward()
    optimizer.step()

# generate from the model
context = torch.zeros((1, 1), dtype=torch.long, device=device)
print(str_decoder(m.generate(context, max_new_tokens=500)[0].tolist()))
#open('more.txt', 'w').write(decode(m.generate(context, max_new_tokens=10000)[0].tolist()))

token embedding table: Embedding(65, 384)

positional embedding table: Embedding(8, 384)

Linear(in_features=384, out_features=64, bias=False) 

Linear(in_features=384, out_features=64, bias=False) 

Linear(in_features=384, out_features=64, bias=False) 

<bound method Module.register_buffer of Head(
  (weighted_key): Linear(in_features=384, out_features=64, bias=False)
  (weighted_query): Linear(in_features=384, out_features=64, bias=False)
  (weighted_value): Linear(in_features=384, out_features=64, bias=False)
)> 

Linear(in_features=384, out_features=64, bias=False) 

Linear(in_features=384, out_features=64, bias=False) 

Linear(in_features=384, out_features=64, bias=False) 

<bound method Module.register_buffer of Head(
  (weighted_key): Linear(in_features=384, out_features=64, bias=False)
  (weighted_query): Linear(in_features=384, out_features=64, bias=False)
  (weighted_value): Linear(in_features=384, out_features=64, bias=False)
)> 

Linear(in_features=384, out_features=64, bia

TypeError: 'Tensor' object is not callable

In [ ]:
text[:100]

In [ ]:
torch.manual_seed(42)
a = torch.randint(12, (2, 3, 4))
b = torch.randint(12, (2, 3, 4))
a, '\n', b
c = a @ b.transpose(-2, -1)
c

In [ ]:
b.shape

In [ ]:
b.shape[2]

In [ ]:
a = torch.randint(10,(3, 4))
b = torch.tril(a)
b

In [ ]:
import torch
from torch import nn
class MyModule(nn.Module):
    def __init__(self) -> None:
        super().__init__()
        self.linears = nn.ModuleList([nn.Linear(2, 2) for i in range(3)])

    def forward(self, x):
        # ModuleList can act as an iterable, or be indexed using ints
        for i, l in enumerate(self.linears):
            x = self.linears[i // 2](x) + l(x)
        return x

m = MyModule()

In [ ]:
m

In [ ]:
c = torch.rand((2,2))
print(c)

In [ ]:
c.shape

In [ ]:
d = m(c)
print(d)

In [ ]:
import torch
from torch import nn
class something(nn.Module):

  def __init__(self, input):
    super().__init__()
    self.layer = nn.Linear(3, input*6, bias = False)

  def forward(self, x):
    return self.layer(x)

In [ ]:
k = something(7)
k

In [ ]:
import torch

In [ ]:
a = torch.tensor([1, 2, 3])
b = torch.tensor([4, 5, 6])
a, b

In [ ]:
c = torch.stack([a, b])
c



---

# Once Again...

In [1]:
# import necessary libraries

import torch
from torch import nn
from torch.nn import functional as F

In [2]:
# initializing hyperparameters
batch_size = 64
block_size = 256 # context-length or total sequences
max_iters = 5000 # total number of training steps that would run for exactly 5000 steps then stops.
eval_interval = 500 # every 500 steps, pause training and check progress. so this eval stops at steps 500, 1000, 1500 etc
eval_iters = 200 # when evaluating, how many batches to average the loss over as average would give stable estimate
learning_rate = 0.0003
device = 'cuda' if torch.cuda.is_available() else 'cpu' # setting up device agnostics
embedding_size = 384 # length of list of numbers or embedding vector for every chars aka channels (C)
num_heads = 6 # total heads that would need in performinh attentions
num_layers = 6 # num of layers in tranformer block
dropout = 0.2 # randomly zero 20% of the neurons/weights

In [3]:
# get a batch for training and eval

torch.manual_seed(42)
torch.cuda.manual_seed(42)

# get the dataset
!wget https://raw.githubusercontent.com/karpathy/char-rnn/master/data/tinyshakespeare/input.txt
with open('input.txt', 'r', encoding='utf-8') as f: # the encoding is added to make sure special chars in shakespeare are read correctly.
  text = f.read()

chars = sorted(set(list(text)))
vocab_size = len(chars)
print(f'Total length of vocabulary is: {vocab_size} \n')

# creating encoder decoder
string_to_int = {ch:i for i, ch in enumerate(chars)}
print(f'The encoded (string to integer) is: {string_to_int} \n')
int_to_string = {i:ch for i, ch in enumerate(chars)}
print(f'The decoded (integer to string) is: {int_to_string} \n')

encoder = lambda string: [string_to_int[c] for c in string]
decoder = lambda integer: ''.join([int_to_string[i] for i in integer])

# Creating training eval split
data = torch.tensor(encoder(text), dtype = torch.long)
length = int(0.9 * len(data))
train_data = data[:length]
val_data = data[length:]

--2026-06-05 16:54:06--  https://raw.githubusercontent.com/karpathy/char-rnn/master/data/tinyshakespeare/input.txt
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1115394 (1.1M) [text/plain]
Saving to: ‘input.txt’

input.txt           100%[===================>]   1.06M  --.-KB/s    in 0.007s  

2026-06-05 16:54:06 (163 MB/s) - ‘input.txt’ saved [1115394/1115394]

Total length of vocabulary is: 65 

The encoded (string to integer) is: {'\n': 0, ' ': 1, '!': 2, '$': 3, '&': 4, "'": 5, ',': 6, '-': 7, '.': 8, '3': 9, ':': 10, ';': 11, '?': 12, 'A': 13, 'B': 14, 'C': 15, 'D': 16, 'E': 17, 'F': 18, 'G': 19, 'H': 20, 'I': 21, 'J': 22, 'K': 23, 'L': 24, 'M': 25, 'N': 26, 'O': 27, 'P': 28, 'Q': 29, 'R': 30, 'S': 31, 'T': 32, 'U': 33, 'V': 34, 'W': 35, 'X': 36, 'Y': 

During training, we can't feed entire dataset at once. That's why we randomly grab a chunk of the dataset with a batch_size of sequences each of block_size length.

In [4]:
# Choose which data to sample from - training or validation.
def get_batch(split: str):
  data = train_data if split == 'train' else val_data

  # Randomly pick batch_size size of list of numbers. Subtrack block_size size to ensure we dont start too close
  # to end and run out of characters
  ix = torch.randint(len(data) - block_size, (batch_size,))

  # x is the input - block_size characters from each starting position
  # y is the target - same but shifted or off set by one ahead.
  # So, at every position, the next character / the target is what we are trying to predict
  x = torch.stack([data[i : i + block_size] for i in ix])
  y = torch.stack([data[i + 1 : i + block_size + 1] for i in ix])

  # move x and y to target device
  x, y = x.to(device), y.to(device)

  return x, y

In [5]:
a = torch.randint(len(train_data) - block_size, (batch_size,))
a, a.shape

(tensor([873546, 864083, 650212,  21984, 621090, 744407,    544, 262632, 695084,
         975727, 591512, 852668, 574906, 388884, 864043, 129628, 515259, 409917,
         246627, 524276,  93125, 418758, 799373, 846889, 497823, 603645, 722557,
         333975, 133043, 239111, 895540, 556964,  25879, 614363, 734223, 241624,
         540635, 699772, 336524, 812500, 468622, 233644, 977169, 711517, 254207,
         255257, 874077, 161686, 785995, 759251, 215790, 427401, 519678, 775411,
         704486, 807713, 280285, 546178, 790574, 175268,  30466, 424852, 772598,
         946214]),
 torch.Size([64]))

**estimate_loss** - One batch gives a noisy **loss** estimate. This function averages the loss over **eval_iters** number of batches to get stable picture of how well the model is doing. Called every **eval_interval** steps.

In [6]:
@torch.inference_mode() # -> we are not updating any weights, so we dont need to track the gradients.
# This saves memoery and speed things up.

def estimate_loss():

  # create an empty dict to store the results.
  out = {}

  # switch the model to eval mode
  model.eval()

  # for each split, run eval_iters (200) batches through the model, collect each loss, then average the loss.
  # store results in dict with split name as key
  for split in ['train', 'val']:
    losses = torch.zeros(eval_iters) # this would create a tensors of zeros of size eval_iters. these would
    # later get replaced by the actual losses
    # print(f'Initial tensor of zeros for losses variable looks like: {losses} \n')

    for k in range(eval_iters):
      X, Y = get_batch(split)
      logits, loss = model(X, Y)
      losses[k] = loss.item()
    out[split] = losses.mean()

  # print(f'now the losses is \n{losses} \n and the average is\n {out} before model goes again in training mode \n')

  # switch back to train mode
  model.train()

  return out


In [7]:
b = torch.zeros(eval_iters)
b.shape

torch.Size([200])

**Head** - Single attention head

This is the core of the transformer. The concept of head is to recognize some pattern that can form a relationship in order to predict the next character by looking back at the previous tokens and decide how much to attend to each one.

A head usually comprises of three things - K(key), Q(query) and V(value).

K -> what do I contain?

Q -> what am I looking for?

V -> what value do I give if selected?

These three are also a linear layers - starts with random value at first and over training these become meaningful.

These three are for each token. Same input `x`, three different transformations.

**nn.Linear(embedding_size, head_size)** - in_features = C numbers, out_features = head_size numbers out. No bias because attention doesn't need it.

What do we need to create the **Head class**

- As seen above, when we create the head class, we need the head size - meaning the size of the heads we want to work on each slice or each section of the C. num_heads which we will see later, defines how many heads we want. the size of head is calculated by dividing C by num_heads. So if C is 6 and num_heads is 2 meaning (6/2=3) 3 head sizes or 3 heads of size 3 (not the tuple size) will work on 2 slices or 2 sections of C. First 2 elements would have head 1, the middle two will have head 2 and last two elements would have head 3. This is for understanding only.

- We will also need a triagular matrix say a matrix of lower triangle filled with ones and upper one with zeros.
We will use **register_buffer** method inside it we would create a triangular mask using torch.tril defining the ones and the size of it. It is not a learnable parameter. It moves to GPU with model automatically.

[[1, 0, 0, 0, 0],

 [1, 1, 0, 0, 0],

 [1, 1, 1, 0, 0],

 [1, 1, 1, 1, 0],

 [1, 1, 1, 1, 1]]

Purpose is we need to prevent tokens from looking at future tokes. We can't look ahead when predicting the next character, future tokens don't exist yet during generation.

- Then we randomly zero out some attention weights during training.

In [8]:
class Head(nn.Module):

  def __init__(self, head_size):

    super().__init__()

    self.key = nn.Linear(in_features = embedding_size, out_features = head_size, bias = False)
    self.query = nn.Linear(embedding_size, head_size, bias = False)
    self.value = nn.Linear(embedding_size, head_size, bias = False)

    # creating the triangular mask
    self.register_buffer('tril', torch.tril(torch.ones(block_size, block_size)))

    self.dropout = nn.Dropout(dropout)

  # Unpack dimensions. Compute key and query, every token simultaneuously gets its "what I contain" and "what i am looking for" vectors.

  def forward(self, x):
    B, T, C = x.shape
    k = self.key(x) # B, T, head_size
    q = self.query(x) # B, T, head_size

    # Compute attention scores. Every token's query dot producted against every token;s key to measure the relevance between every pair.
    # i.e. how well the score is between what i am looking for x what do i contain.
    # Dividing by sqrt(head_size) to keep the scores stable.
    wei = q @ k.transpose(-2, -1) * k.shape[-1]**-0.5
    # print(f'shape of wei is: {wei.shape} \n')

    # mask future tokens. Find positions where tril == 0 i.e. the upper triangle and replace those with -inf.
    # After softmax these becomes exactly 0 meaning future tokens contribute nothing.
    wei = wei.masked_fill(self.tril[:T, :T] == 0, float('-inf'))

    # convert the scores to prob resulting each row sum to 1. These will be the attention weights. Dropout as well.
    wei = F.softmax(wei, dim=-1)
    wei = self.dropout(wei)

    # Compute the value vectors Weight sum of values each token collects info from relevant past tokens, weighted by attention scores.
    v = self.value(x)
    out = wei @ v
    # print(f'The output shape is {out.shape}\n')
    return out

In [9]:
a = torch.randint((4), (2,3,4))
b = torch.randint((4), (2,3,4))
a, b

(tensor([[[2, 1, 3, 0],
          [3, 1, 1, 1],
          [0, 1, 0, 1]],
 
         [[3, 3, 2, 3],
          [2, 3, 0, 3],
          [2, 2, 1, 0]]]),
 tensor([[[3, 1, 3, 3],
          [1, 1, 1, 1],
          [1, 3, 1, 0]],
 
         [[2, 1, 1, 3],
          [1, 1, 1, 3],
          [1, 2, 3, 2]]]))

In [10]:
b.transpose(-2, -1)

tensor([[[3, 1, 1],
         [1, 1, 3],
         [3, 1, 1],
         [3, 1, 0]],

        [[2, 1, 1],
         [1, 1, 2],
         [1, 1, 3],
         [3, 3, 2]]])

In [11]:
b[-1]

tensor([[2, 1, 1, 3],
        [1, 1, 1, 3],
        [1, 2, 3, 2]])

**Multi Head Attention**

Runs multiple `Head` in parallel, combine their outputs, projects back to original size.

In [12]:
class MultiHeadAttention(nn.Module):

  def __init__(self, num_heads, head_size):

    super().__init__()
    # Create num_heads independent Head objects. Each head learns different relationships simultaneously.
    # nn.ModuleList is a pytorch aware list where it register each head's psrameters for training
    self.heads = nn.ModuleList([Head(head_size) for i in range(num_heads)])

    # we will use something called projection layer where it maps concatenated outputs back to
    # embedding_size. After concatenation, head_size * num_heads = embedding_size
    # Dropout for regularization.

    self.proj = nn.Linear(head_size * num_heads, embedding_size)
    self.dropout = nn.Dropout(dropout)

  # Run every head on input x independently and then concatenate along last dim, join their o/ps
  # side to sidek=.So the shape goes from (B, T, head_size) per head to (B, T, C) combined

  def forward(self, x):
    # project back to embedding_size/C. This mixes info accross heads. Dropout. Return the enriched
    # token representation.
    out = torch.cat([h(x) for h in self.heads], dim=-1)
    out = self.dropout(self.proj(out))
    return out

**FeedForward**

When the token interacts with each other through attemtion, each token independentaly thinks about what it learned. That thinking step is a small neural network applied to each token separately.

- We want to widen the capacity of C to learn more complex patterns.

- Introduce non-linearity

- compress back to original C size. This keeps the shape of C consistent.

- Regularization for better training

In [13]:
class FeedForward(nn.Module):

  def __init__(self, embedding_size):

    super().__init__()

    self.net = nn.Sequential(
        # widen the C for more capacity to learn
        nn.Linear(embedding_size, 4 * embedding_size),
        # introduce non-linearity
        nn.ReLU(),
        #Compress back to original C size to maintain the shape of C
        nn.Linear(4 * embedding_size, embedding_size),

        # regularization
        nn.Dropout(dropout)
    )

  # Pass x through all the four operations in sequence.
  def forward(self, x):
    return self.net(x)

**Block**

It is a one complete transformer block. It combines multi-head attention and the feedforward into single reusable unit.

- Divide the embedding_size(C) with the number of heads equally across heads

- use multiheadattention class for communication

- use feedforward class for computation

- layer normalization before multiheadattention and feedforward. We need Layer norm to stabilize the scale of the computation. If the token h after attention becomes: `[152.3, -98.4, 203.1, -445.2]`

- When these large numbers go into feedforward:
  nn.Linear: `152.3 * weight + (-89.4) * weight + ...` The result will explode. Large numbers make the gradients unstable, training becomes unreliable. Layer norm rescales the numbers to stable stage:

  `before: [152.3, -89.4, 203.1, -445.2]`

  `after: [0.8, -0.3, 1.1, -1.6]`  <-- same person, stable scale

  Layer norm doesn't change the relationship between the numbers. It just brings them to consistent scale so each layer receives input it can work with reliably.


In [14]:
class Block(nn.Module):

  def __init__(self, embedding_size, num_heads):

    super().__init__()

    # divide the C with num_heads to equally distribute
    head_size = embedding_size // num_heads

    # use multiheadattention for communication
    self.self_attn = MultiHeadAttention(num_heads, head_size)

    # use feedforward for computation
    self.ffwd = FeedForward(embedding_size)

    # layer norm 1
    self.ln1 = nn.LayerNorm(embedding_size)

    # layer norm 2
    self.ln2 = nn.LayerNorm(embedding_size)

  # this is where the layer norm actually works to stabilize. Above we just defined the tools
  def forward(self, x):

    # step 1: normalize -> attention -> add back
    x = x + self.self_attn(self.ln1(x))

    # step 2: normalize -> compute -> add back
    x = x + self.ffwd(self.ln2(x))

    return x


**GPTLanguageModel**

The full model that assembles all the components together that we defined above (those classes and functions).
Takes token IDs as input, predicts new token.

- Convert the normal token IDs into a rich representation hence, embedding look up table.

- also create a positional embedding look up table to take care of repititive chars. This will help the current char to decide which previous token it should pay more attention to.

- 6 layers of transformer block. Chain them using Sequential. The output of one block feeds directly into next one.

- one last layer norm after all blocks i.e. one last stabilization before prediction.

- lm_head - language model head. It projects from C to the vocab_size. Produces one score per possible next char. Shape (embeddiing_size, vocab_size)

- forward pass: here we first unpack the raw token IDs into B and T.

  - take those through first, embedding table.
  - and then create a positional embedding table for each position in the sequence (T)
  - Add them together to create a complete picture for the attention and trasformer

- Pass through all 6 transformer blocks. This is where token communicate (multi head attention) and compute (feedforward)

- Final layer norm to stabilize

- Output head i.e. project from C to vocab_size - once score per possible next character.

In [15]:
class GPTLanguageModelV1(nn.Module):

  def __init__(self):

    super().__init__()

    self.token_embedding_lookup_table = nn.Embedding(vocab_size, embedding_size)
    self.position_embedding_lookup_table = nn.Embedding(block_size, embedding_size)

    layers = []
    for _ in range(num_layers): # Pass through all 6 transformer blocks. Here the tokens communicate and compute
      layer = Block(embedding_size, num_heads)
      layers.append(layer)

    self.blocks = nn.Sequential(*layers) # the * unpacks the list into individual arguments

    self.final_ln = nn.LayerNorm(embedding_size)
    self.lm_head = nn.Linear(embedding_size, vocab_size)

  def forward(self, idx, targets = None):

    B, T = idx.shape
    token_emb = self.token_embedding_lookup_table(idx) # B, T, C
    pos_emb = self.position_embedding_lookup_table(torch.arange(T, device = device)) # (T, C)
    x = token_emb + pos_emb # (B, T, C)
    x = self.blocks(x) # (B, T, C)
    x = self.final_ln(x) # (B, T, C)
    logits = self.lm_head(x) # (B, T, vocab_size)

    if targets is None:
      loss = None

    else:
      B, T, C = logits.shape
      logits = logits.view(B*T, C)
      targets = targets.view(B*T)
      loss = F.cross_entropy(logits, targets)

    return logits, loss

  #

  def generate(self, idx, max_new_tokens):

    for _ in range(max_new_tokens):

      idx_cond = idx[:, -block_size:]

      logits, loss = self(idx_cond)

      logits = logits[:, -1, :]

      probs = F.softmax(logits, dim = -1)

      idx_next = torch.multinomial(probs, num_samples = 1)

      idx = torch.cat((idx, idx_next), dim = 1)

    return idx

**generate**

We give model a starting character. It predicts the next one. Appends it. Predicts the next one. Appends it. Keep going until it has generated `max_new_tokens` characters.

- We'll crop the incoming idx to last `block_size` tokens. Our position embedding lookup table only has `block_size` rows. if the sequence grows longer than `block_size`, we can't look up positions beyond that. So we only feed the last `block_size` tokens.



In [16]:
model = GPTLanguageModelV1()
m = model.to(device)
print(sum(p.numel() for p in m.parameters())/1e6, 'M parameters')

optimizer = torch.optim.AdamW(model.parameters(), lr = learning_rate)

for iter in range(max_iters):

  if iter % eval_interval == 0 or iter == max_iters - 1:
    losses = estimate_loss()
    print(f"step {iter}: train loss {losses['train']:.4f}, val loss {losses['val']:.4f}")

  xb, yb = get_batch('train')

  logits, loss = model(xb, yb)
  optimizer.zero_grad(set_to_none = True)
  loss.backward()
  optimizer.step()

context = torch.zeros((1, 1), dtype = torch.long, device = device)
print(decoder(m.generate(context, max_new_tokens = 500)[0].tolist()))

10.788929 M parameters
step 0: train loss 4.3695, val loss 4.3694
step 500: train loss 1.9081, val loss 2.0073
step 1000: train loss 1.5497, val loss 1.7300
step 1500: train loss 1.4081, val loss 1.6265
step 2000: train loss 1.3225, val loss 1.5660
step 2500: train loss 1.2616, val loss 1.5221
step 3000: train loss 1.2136, val loss 1.5050
step 3500: train loss 1.1725, val loss 1.4891
step 4000: train loss 1.1377, val loss 1.4777
step 4500: train loss 1.1039, val loss 1.4831
step 4999: train loss 1.0724, val loss 1.4914

VIRGILIA:
What! what thou art?

MERCUTIO:
Not, I hear me with thy love red to give me now.

FLORIZEL:
What, some, because torceans?

BRAKENBURY:
I say, again this turn.

Both:
I crown ye; then be till myself and unflice.

ELBOW:
How long I give inderchance while you have been a sellen'd?

SOMERSET:
I will that, sir, unless our arty a felligent,
A midture, open some advouch, one soar, here's house.

ESCALUS:
What is held you will?

BUCKINGHAM:
Nay, are your scotled.

GLO

In [17]:
a = torch.arange(2, 16, 3)
a

tensor([ 2,  5,  8, 11, 14])