<a href="https://colab.research.google.com/github/SauravSG/Deep-Learning/blob/main/CH_00_PyTorch_Fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch

In [ ]:
torch.__version__

'2.9.0+cu126'

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [ ]:
!nvidia-smi

Sat Jan 10 18:33:42 2026       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.15              Driver Version: 550.54.15      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   54C    P8             10W /   70W |       0MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

# **CH 00: Introduction to Tensors**
A tensor is numerical data, both for input encodings and for model outputs, and it is stored as matrices or higher-dimensional arrays. A tensor is a multi-dimensional array of numbers It can represent:
A single number (0D) i.e. a Scalar,
A vector (1D),
A matrix (2D),
Higher-dimensional data (3D, 4D, …)

---
###*Creating Tensors*

In [ ]:
#scalar
scalar = torch.tensor(7)
print(scalar)

tensor(7)


**torch.tensor** is a PyTorch function used to create a tensor from data.

What it does:
- Takes numbers (list, array, scalar)
- Converts them into a PyTorch tensor
- Stores them in a format PyTorch can compute with

In [ ]:
scalar.ndim

0

In [ ]:
# to get the tensor back as a python integer
scalar.item()

7

In [ ]:
# vector - 1D
vector = torch.tensor([1,2])
print(vector, '\n')
print(f'The dim of Vector is {vector.ndim} \n')
print(f'The shape of the VEctor is {vector.shape}') #(1,2) but it will only display 2.

tensor([1, 2]) 

The dim of Vector is 1 

The shape of the VEctor is torch.Size([2])


In [ ]:
#Matrix
Matrix = torch.tensor([[1, 2, 3],
                       [4, 5, 6]])
print(Matrix, '\n')
print(f'Dim of Matrix = {Matrix.ndim} \n')
print(f'Shape of Matrix = {Matrix.shape}') #(2,3) 2 rows 3 cols

tensor([[1, 2, 3],
        [4, 5, 6]]) 

Dim of Matrix = 2 

Shape of Matrix = torch.Size([2, 3])


In [ ]:
#tensor - for 2D+ we can ay
Tensor = torch.tensor([[[1, 2, 3],
                        [4, 5, 6],
                        [7, 8, 9]]])
print(Tensor, '\n')
print(f'The dim of Tensor = {Tensor.ndim} \n')
print(f'Shape of Tensor = {Tensor.shape}') # meaning 1 layer, 3 rows, 3 columns

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]]) 

The dim of Tensor = 3 

Shape of Tensor = torch.Size([1, 3, 3])


#### Random Tensors

Why random tensors?

-> Random tensors are important because the way many NN learns is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

```Start with random numbers -> look at data -> update random numbers -> update random numbers```

> Resource: https://www.learnpytorch.io/00_pytorch_fundamentals/#:~:text=Upper%20(X)-,Random%20tensors,-%C2%B6



In [ ]:
# create a random tensors of size (3, 4)
random_tensor = torch.rand(3, 4) # or random_tensor = torch.rand(size=(3, 4))
print(random_tensor, '\n')
print(random_tensor.ndim)

tensor([[0.3644, 0.5902, 0.1996, 0.3826],
        [0.2839, 0.2017, 0.2294, 0.1892],
        [0.7890, 0.8728, 0.7769, 0.2923]]) 

2


In [ ]:
# to create random tensor of integers from range 1 to 12 of size (3,4)
r = torch.randint(1, 12, (3, 4))
print(r)

tensor([[ 2,  4,  3,  8],
        [ 6, 11,  4,  7],
        [ 4, 11,  9,  2]])


In [ ]:
# create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(244, 244, 3)) # height, width, colour channel meaning R, G, B
print(random_image_size_tensor.shape, '\n')
print(random_image_size_tensor.ndim, '\n')

#this is just for a demonstration of an image with height and width of 244x244 it will be then filtered or divided into R, G, B. And that;s how the image with be converted into
# numerical encoding/numbers. But here we created one random tensor.

#something like: https://www.learnpytorch.io/00_pytorch_fundamentals/#:~:text=%5Bcolour_channels%2C%20height%2C%20width%5D

torch.Size([244, 244, 3]) 

3 



#### Zeros and Ones

In [ ]:
# create a tensors of all zeros
zeros = torch.zeros(size=(3, 4), dtype=torch.int16) # if want integers otherwise floats by default
print(zeros)

tensor([[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]], dtype=torch.int16)


In [ ]:
# a glimpse of matrix multiplication
zeros*r

tensor([[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]])

In [ ]:
# create tensor full of ones
ones = torch.ones(size=(3, 4))
print(ones)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])


In [ ]:
ones.dtype

torch.float32

* Creating a range of tensors and tensor-like

In [ ]:
# use torch.arange()
one_to_ten = torch.arange(1, 11)
print(one_to_ten, '\n')
with_steps = torch.arange(start=0, end=1000, step=77)
print(with_steps)

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]) 

tensor([  0,  77, 154, 231, 308, 385, 462, 539, 616, 693, 770, 847, 924])


- "*_like" tensor methods:
In PyTorch, tensor_like methods create a new tensor that has the same shape (and often dtype/device) as an existing tensor.
They are used when you want a tensor that matches another tensor’s structure.



In [ ]:
# create a tensor of zeros like one_to_ten
zeros_like = torch.zeros_like(one_to_ten) #or torch.zeros_like(intput=one_to_ten)
print(zeros_like)

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])


#### Tensor Datatypes

**Note:** Tensor datatypes is one of the 3 big errors you'll run into with PyTorch & deep learning:
1. Tensors not right datatype. (if there's a mismatch between the dtype of two tensors i.e. one is float32 and float16, that would throw error)
2. Tensors not right shape (mismatch between shapes of tensors)
3. Tensors not on the right device (i.e. cpu or cuda)

In [ ]:
# float32 tensor
float32_tensor = torch.tensor([3.0, 6.2, 8.4],
                              dtype = None, # dtype of tensor like float32 or float16
                              device=None, # what device is your tensor on like cuda or cpu
                              requires_grad=False # whether or not track gradients with this tensor operation
                              )
print(float32_tensor)
#by default data type is float, PyTorch shows 4 decimal places by default for float tensors.
# # the 16, 32, or 64 indicate how many bits are used to store the number.
# larger bit-size → higher precision
# smaller bit-size → lower precision

tensor([3.0000, 6.2000, 8.4000])


* a way to tackle the first error of tensors i.e. dtype mismatch - we can convert from one to another dtype

In [ ]:
#converted the float32 tensor to float16 tensor
float16_tensor = float32_tensor.type(torch.float16)
print(float16_tensor, float16_tensor.dtype)

# float16 has much lower precision
#Some decimal values cannot be represented exactly
#Values are approximated, not rounded arbitrarily

tensor([3.0000, 6.1992, 8.3984], dtype=torch.float16) torch.float16


In [ ]:
float16_tensor * float32_tensor

tensor([ 9.0000, 38.4352, 70.5469])

In [ ]:
float64_tensor = torch.tensor([7.9, 9.0, 5.0], dtype=torch.float64)
print(float64_tensor)

tensor([7.9000, 9.0000, 5.0000], dtype=torch.float64)


In [ ]:
float16_tensor * float64_tensor

tensor([23.7000, 55.7930, 41.9922], dtype=torch.float64)

In [ ]:
int32_tensor = torch.tensor([1, 2, 3], dtype=torch.int16)
print(int32_tensor)

tensor([1, 2, 3], dtype=torch.int16)


In [ ]:
float16_tensor * int32_tensor

tensor([ 3.0000, 12.3984, 25.1875], dtype=torch.float16)

* the error will mostly when working with large NN. And if we know there's any datatype issue, we know what to check.

#### Getting information from tensors.

1. Tensors not right datatype. (if there's a mismatch between the dtype of two tensors i.e. one is float32 and float16, that would throw error) - use tensor.dtype
2. Tensors not right shape (mismatch between shapes of tensors) - use tensor.shape
3. Tensors not on the right device (i.e. cpu or cuda) - use tensor.device

In [ ]:
some_tensor = torch.rand(3, 4)
print(some_tensor)

tensor([[0.3464, 0.1557, 0.8703, 0.3729],
        [0.6960, 0.0977, 0.9838, 0.8757],
        [0.8722, 0.7727, 0.0407, 0.6806]])


In [ ]:
# find out about tensor
print(f'The shape of tensor is: {some_tensor.shape} \n')
print(f'Datatype of tensor is: {some_tensor.dtype} \n')
print(f'Device tensor is  on: {some_tensor.device} \n')


The shape of tensor is: torch.Size([3, 4]) 

Datatype of tensor is: torch.float32 

Device tensor is  on: cpu 



### Manipulating Tensors (Tensor operations)
Tensor operations includes:
* Addition
* Substraction
* Multiplication (element-wise)
* Division
* Matrix Multiplication

In [ ]:
# Addition
tensor = torch.tensor([1, 2, 3])
print(tensor + 10)

tensor([11, 12, 13])


In [ ]:
#multiply
print(tensor * 10)

tensor([10, 20, 30])


##### Note: we are manipulating the tensor here. The original tensor won't change unless operations assigned as a variable.

In [ ]:
# subtract
print(tensor - 10)

tensor([-9, -8, -7])


In [ ]:
# try out pytorch inbuilt fn
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [ ]:
torch.add(tensor, 20)

tensor([21, 22, 23])

##### Matrix multiplication
##### - Two main ways of performing multiplication in neural networks and deep learning:
1. Element-wise multiplication
2. Matrix multiplication

There are 2 main rules that performing matrix multiplication needs to satisfy:
1. The **inner dimensions** must match:

* `(3, 2) @ (3, 2)` - won't work

* `(2, 3) @ (3, 2)` - work

* `(3, 2) @ (2, 3)` - work.

2. The resulting matrix  has the shape of the **outer dimensions**:
* `(2, 3) @ (3, 2)` -> `(2, 2)`
* `(3, 2) @ (2, 3)` -> `(3, 3)`

In [ ]:
# 1. element wise
print(tensor, '*', tensor)
print(f'Equals: {tensor * tensor}')

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [ ]:
# 2. Matrix multiplication although we are doing vector multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [ ]:
# matrix multiplication by hand
1*1 + 2*2 + 3*3

14

###### just to see the difference between by hand and pytorch in built method

In [ ]:
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
print(value)

tensor(14)
CPU times: user 700 µs, sys: 1.06 ms, total: 1.76 ms
Wall time: 4.85 ms


In [ ]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 409 µs, sys: 38 µs, total: 447 µs
Wall time: 361 µs


tensor(14)

###### One of the most common errors in DL: shape errors

In [ ]:
# will throw inner since the inner dimentions mismatch
torch.matmul(torch.rand(3, 2), torch.rand(3, 2))

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [ ]:
# will work
torch.matmul(torch.rand(3, 2), torch.rand(2, 3))

tensor([[0.1698, 0.1864, 0.1700],
        [0.4342, 0.2944, 0.5398],
        [0.7982, 0.8391, 0.8205]])

In [ ]:
# shapes for matrix multiplication
tensor_A = torch.tensor([[1, 2],
                        [3, 4],
                        [5, 6]])
tensor_B = torch.tensor([[7, 10],
                        [8, 11],
                        [9, 12]])

torch.mm(tensor_A, tensor_B) #.mm is same as .matmul. More like an alias.

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

To fix our tensor shape issues, we can manipulate one of our matrix using **Transpose**.

A **Transpose** switches the axes or dimensions of a given tensor.


In [ ]:
print(f"Original tensor: \n {tensor_B} \n and it's shape is {tensor_B.shape}\n")
print(f'After doing Transpose: \n {tensor_B.T} \n')
print(f'Now the shape after transpose is: \n {tensor_B.T.shape}')

Original tensor: 
 tensor([[ 7, 10],
        [ 8, 11],
        [ 9, 12]]) 
 and it's shape is torch.Size([3, 2])

After doing Transpose: 
 tensor([[ 7,  8,  9],
        [10, 11, 12]]) 

Now the shape after transpose is: 
 torch.Size([2, 3])


In [ ]:
print(f'After the Transpose, the Matrix Multiplication will now throw error due to same inner dimensions \n')
print(torch.mm(tensor_A, tensor_B.T), '\n')
print(f'Now the outer dimension will match as well: {torch.mm(tensor_A, tensor_B.T).shape}')

After the Transpose, the Matrix Multiplication will now throw error due to same inner dimensions 

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]]) 

Now the outer dimension will match as well: torch.Size([3, 3])


#### Finding the min, max, mean, sum, etc (tensor aggregation)

In [ ]:
# creating tensor
x = torch.arange(0, 100, 10)
print(x)

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])


In [ ]:
# finding min
print(x.min()) # or torch.min(x)

tensor(0)


In [ ]:
#finding max
print(torch.max(x))

tensor(90)


In [ ]:
# finding mean/avg
%%time
print(x.type(torch.float32).mean()) #or print(torch.mean(x.type(torch.float32)))

tensor(45.)
CPU times: user 1.83 ms, sys: 0 ns, total: 1.83 ms
Wall time: 1.56 ms


In [ ]:
%%time
print(torch.mean(x.type(torch.float32)))

tensor(45.)
CPU times: user 1.76 ms, sys: 0 ns, total: 1.76 ms
Wall time: 1.63 ms


* In the above example, we had to convert to float dtype as the mean() doesn't take the input in int or long datatype.

In [ ]:
#find sum
print(torch.sum(x)) # or print(x.sum())

tensor(450)


In [ ]:
# finding index of max and min.The argmin() and argmax() functions returns the indices of min and max respectively among the overall tensor
print(x.argmax(), x.argmin())

tensor(9) tensor(0)


###### Reshaping, stacking, squeezing, unsqueezing

* Reshaping - reshapes an i/p tensor at defined shape
* View - return a view of an i/p tensor of certain shape but keep the same memory as the original tensor
* stacking - combine multiple tensors on top (vstack) or side-to-side (hstack)
* squeeze - removes all `1` dimensions from tensor
* Unsqueeze - add a `1` dimension to a target tensor
* Permute - Return a view of the i/p with dimensions permuted (swapped) in a certain way

In [ ]:
new_x = torch.arange(1, 10)
print(new_x, new_x.shape)

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]) torch.Size([9])


In [ ]:
# 1. reshaping
# add an extra dimension
new_x_reshaped = new_x.reshape(1, 7)
print(new_x_reshaped) # will throw error: shape '[1, 7]' is invalid for input of size 9

RuntimeError: shape '[1, 7]' is invalid for input of size 9

In [ ]:
new_x_reshaped = new_x.reshape(9, 1)
print(new_x_reshaped, new_x_reshaped.shape)

tensor([[1],
        [2],
        [3],
        [4],
        [5],
        [6],
        [7],
        [8],
        [9]]) torch.Size([9, 1])


**Note:** The reshaping works as long as the new shape is multiple of the original one

In [ ]:
# change the view
y = new_x.view(1, 9)
print(y, y.shape)

tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]]) torch.Size([1, 9])


In [ ]:
# changing y, changes x because a view of a tensor shares the same memory as the original one
y[:, 0] = 5
print(new_x, '\n' ,y)

tensor([5, 2, 3, 4, 5, 6, 7, 8, 9]) 
 tensor([[5, 2, 3, 4, 5, 6, 7, 8, 9]])


In [ ]:
# stack tensors on top of each other based on the dimensions 0 or 1 or even 2 if the original tensor is compatible
x_stacked = torch.stack([new_x, new_x, new_x, new_x], dim = 0)
print(x_stacked, x_stacked.shape)

tensor([[5, 2, 3, 4, 5, 6, 7, 8, 9],
        [5, 2, 3, 4, 5, 6, 7, 8, 9],
        [5, 2, 3, 4, 5, 6, 7, 8, 9],
        [5, 2, 3, 4, 5, 6, 7, 8, 9]]) torch.Size([4, 9])


In [ ]:
# .vstack() - this stacks the tensors on top of other
y_vstack = torch.vstack([new_x, new_x])
print(y_vstack, y_vstack.shape)

tensor([[5, 2, 3, 4, 5, 6, 7, 8, 9],
        [5, 2, 3, 4, 5, 6, 7, 8, 9]]) torch.Size([2, 9])


In [ ]:
# .hstack() - this stacks the tensors side to side
x_hstack = torch.hstack([new_x, new_x])
print(x_hstack, x_hstack.shape)

tensor([5, 2, 3, 4, 5, 6, 7, 8, 9, 5, 2, 3, 4, 5, 6, 7, 8, 9]) torch.Size([18])


In [ ]:
new = torch.tensor([[1, 2, 3],
                    [4, 5, 6]])
print(f'Here, in case of vstack, the tensors will be on top of another: \n{torch.vstack([new, new])}.\n And the shape would be {torch.vstack([new, new]).shape} \n')
print(f'Here, in case of hstack, the tensors will be side to side: \n{torch.hstack([new, new])}.\n And the shape would be {torch.hstack([new, new]).shape}')

Here, in case of vstack, the tensors will be on top of another: 
tensor([[1, 2, 3],
        [4, 5, 6],
        [1, 2, 3],
        [4, 5, 6]]).
 And the shape would be torch.Size([4, 3]) 

Here, in case of hstack, the tensors will be side to side: 
tensor([[1, 2, 3, 1, 2, 3],
        [4, 5, 6, 4, 5, 6]]).
 And the shape would be torch.Size([2, 6])


In [ ]:
# squeezing - torch.squeeze() removes all single dimensions from a target tensor
x = torch.arange(1, 11)
print(x, x.shape, '\n')
x_reshape = x.reshape(2, 5)
print(x_reshape, x_reshape.shape)

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]) torch.Size([10]) 

tensor([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]]) torch.Size([2, 5])


In [ ]:
print(x.squeeze())

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])


In [ ]:
xx = torch.tensor([[1, 2, 3, 4, 5]])
print(xx, xx.shape, '\n')
print(xx.squeeze(), xx.squeeze().shape)

tensor([[1, 2, 3, 4, 5]]) torch.Size([1, 5]) 

tensor([1, 2, 3, 4, 5]) torch.Size([5])


Correct condition for squeeze():

**squeeze()** removes any dimension whose size is 1, regardless of position.
Can be squeezed:
`(1, 10)   → (10,)`
`(10, 1)   → (10,)`
`(1, 10, 1) → (10,)`
`(3, 1, 5)   → (3, 5)`

Cannot be squeezed:
`(2, 5)`

It is not limited to just:

(1, any_col) or
(any_row, 1)

In [ ]:
#unsqueeze() - adds a single dim to a target tensor at a specific dim

print(f'Previous target: {xx} \n with shape: {xx.shape} \n')

xx_unsqueezed = xx.unsqueeze(dim = 0)
print(f'New tensor: {xx_unsqueezed} \n with shape: {xx_unsqueezed.shape}')

Previous target: tensor([[1, 2, 3, 4, 5]]) 
 with shape: torch.Size([1, 5]) 

New tensor: tensor([[[1, 2, 3, 4, 5]]]) 
 with shape: torch.Size([1, 1, 5])


In [ ]:
#permute - rearranges the dimensions of a target tensor in a specific order

x_original = torch.randn(size=(244, 244, 3)) # [height, width, colur_channels]
print(f'shape of original tensor: \n {x_original.shape} \n')
# permute the original tensor to rearrange the axis (or dim) order

x_permuted = x_original.permute(2, 0, 1)
print(f'New order: \n {x_permuted.shape}')

shape of original tensor: 
 torch.Size([244, 244, 3]) 

New order: 
 torch.Size([3, 244, 244])


##### indexing (selecting data from tensors)

Indexing with PyTorch is similar to NumPy.

In [ ]:
xx_new = torch.arange(1, 10).reshape(1, 3, 3)
print(xx_new, xx_new.shape)

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]]) torch.Size([1, 3, 3])


In [ ]:
# index on first bracket (dim = 0)
xx_new[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
# index on middle bracket (dim = 1)
xx_new[0][0] # same as xx_new[0, 0]

tensor([1, 2, 3])

In [ ]:
# index on inner bracket (last dimension)
xx_new[0][0][0]

tensor(1)

In [ ]:
xx_new[0, 0, 0]

tensor(1)

In [ ]:
print(xx_new[0, 2, 1])

tensor(8)


In [ ]:
# you can use ":" to select "all" of a target dimension
xx_new[:, 0]

tensor([[1, 2, 3]])

In [ ]:
# get all values of 0th and 1st dimension but only index 1 of 2nd dimension
xx_new[:, :, 1]

tensor([[2, 5, 8]])

In [ ]:
# get all values of the 0 dimension but only the 1 index value of 1st and 2nd dimension
xx_new[:, 1, 1]

tensor([5])

In [ ]:
# get index 0 of 0th and 1st deminsion and all values of 2nd dimension

xx_new[0, 0, :]

tensor([1, 2, 3])

In [ ]:
# return element, 9
xx_new[0, 2, 2]

tensor(9)

In [ ]:
# index to return 3, 6, 9
xx_new[:, :, 2]

tensor([[3, 6, 9]])

### PyTorch tensors & NumPy

NumPy is a popular scientific python numerical computing library.

And because of this, PyTorch has functionality to interact with it.

* Data in Numpy, want in PyTorch tensor -> `torch.from_numpy(ndarray)`
* PyTorch tensor -> NumPy -> `torch.Tensor.numpy()`

In [ ]:
import torch
import numpy as np

arr = np.arange(1, 8)
print(arr, '\n')
tensor = torch.from_numpy(arr) # warning: when converting from numpy -> pytorch, pytorch reflects numpy's default datatype of float64 unless specified otherwise
print(tensor)

[1 2 3 4 5 6 7] 

tensor([1, 2, 3, 4, 5, 6, 7])


In [ ]:
# change the value of arr. what this will do to tensor?
arr = arr + 1
print(arr, '\n', tensor) # no change in tensor.

[2 3 4 5 6 7 8] 
 tensor([1, 2, 3, 4, 5, 6, 7])


In [ ]:
# Tensor to numpy arr
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
print(tensor, 'and dtype:', tensor.dtype,'\n', numpy_tensor, 'and dtype:', numpy_tensor.dtype)

tensor([1., 1., 1., 1., 1., 1., 1.]) and dtype: torch.float32 
 [1. 1. 1. 1. 1. 1. 1.] and dtype: float32


In [ ]:
# change the tensor, what happens to `numpy_tensor`?
tensor = tensor + 1
tensor, numpy_tensor # original i.e. tensor remains same not affecting numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

##### Reproducibility: Trying to take random out of random

Getting the same results every time you run the same code.

Without reproducibility:

- Training the same model twice → different weights

- Different loss values

- Hard to debug

- Hard to compare experiments

With reproducibility:

- You can trust comparisons

- You can debug reliably

- Results are repeatable

In short, how a NN learns:
`start with random number -> tensor operations -> update random numbers to try and make them better representations of data -> again -> again...`

To reduce randomness in NN and PyTorch comes the concept of a **random seed**.

Essentially, what the random seed does is the flavour the randomness.

In [ ]:
torch.rand(3, 3)

tensor([[0.0526, 0.4435, 0.9684],
        [0.5999, 0.7329, 0.2389],
        [0.0052, 0.1556, 0.8777]])

In [ ]:
# create two random tensors
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)

print(random_tensor_A, '\n')
print(random_tensor_B, '\n')
print(random_tensor_A == random_tensor_B)

tensor([[0.2926, 0.3810, 0.6802, 0.5556],
        [0.6844, 0.8236, 0.8948, 0.7942],
        [0.2434, 0.4025, 0.9049, 0.1649]]) 

tensor([[0.7669, 0.9212, 0.8979, 0.0965],
        [0.1841, 0.9029, 0.1497, 0.6340],
        [0.0352, 0.9254, 0.1063, 0.4350]]) 

tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [ ]:
# making random but reproducible tensors

# set the random seed
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)

random_tensor_C = torch.rand(3, 4)
random_tensor_D = torch.rand(3, 4)
print(random_tensor_C, '\n')
print(random_tensor_D, '\n')
print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]]) 

tensor([[0.8694, 0.5677, 0.7411, 0.4294],
        [0.8854, 0.5739, 0.2666, 0.6274],
        [0.2696, 0.4414, 0.2969, 0.8317]]) 

tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [ ]:
RANDOM_SEED = 42  # it's like a inner state and the tensors will start from the same state

torch.manual_seed(RANDOM_SEED)

random_tensor_C = torch.rand(3, 4)

torch.manual_seed(RANDOM_SEED) # generator is reset back to the same starting point. Previous random state is discarded.

random_tensor_D = torch.rand(3, 4)
print(random_tensor_C, '\n')
print(random_tensor_D, '\n')
print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]]) 

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]]) 

tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


torch.manual_seed(42)
- Generator is reset back to the same starting point.
- Previous random state is discarded

## Putting tensors (and models) on the GPU

* The reason we want our tensors/models on the GPU is because using a GPU results in faster computations.


In [ ]:
# set device agnostic mode
device = "cuda" if torch.cuda.is_available() else "cpu"
print(device)

cuda


In [ ]:
# count number of devices
torch.cuda.device_count()

1

In [ ]:
# create a tensor (default on the CPU)
tensor = torch.tensor([1, 2, 3])

# tensor not on GPU
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [ ]:
# move tensor to GPU (if available)
tensor_on_gpu = tensor.to(device)
print(tensor_on_gpu) # this will shift fromd default cpu to gpu as declared the deivce in the above cell. The 0 in cuda_0 is the index of the device (in this case: gpu) available.

tensor([1, 2, 3], device='cuda:0')


##### Moving tensors back to CPU

In [ ]:
# if tensors is on GPU, can't transform it to numPy
tensor_on_gpu.numpy()

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [ ]:
# To fix the GPU tensor with NumPy issue, we can first set it to the CPU
tensor_back_on_cpu = tensor_on_gpu.cpu()
print(tensor_back_on_cpu) # this will still print the tensor. we need to move it to numpy
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
print(tensor_back_on_cpu)

tensor([1, 2, 3])
[1 2 3]


#### Exercises & Extra-curriculum:

In [ ]:
# 1. Create a random tensor with shape (7, 7).
ex_random_tensor = torch.randn(7, 7)
print(ex_random_tensor, ex_random_tensor.shape)

tensor([[ 0.1862, -0.0395,  0.5743, -0.1777, -1.3997, -0.1057, -0.6485],
        [-1.1675, -0.9175, -0.2052,  1.9379,  1.3110, -1.6730, -1.0176],
        [ 0.5589,  0.4290,  0.1708, -0.0497, -0.5976, -1.3562,  2.1597],
        [ 0.0661,  0.2513,  1.4357,  0.4368, -1.1029,  0.8914, -0.2455],
        [-1.9473,  1.1453,  0.8549, -0.9487, -0.6075,  1.5813,  0.7845],
        [ 0.0205, -1.1870, -1.2093,  0.4602,  2.1720, -0.8786, -0.4573],
        [-2.8356,  1.0589,  0.1098, -2.1725, -0.3999, -0.5889,  1.2868]]) torch.Size([7, 7])


In [ ]:
# Perform a matrix multiplication on the tensor from 2 with another random tensor with shape (1, 7) (hint: you may have to transpose the second tensor).
ex_random_tensor_1 = torch.randn(1,7)
print(ex_random_tensor_1)
transposed_ex_random_number_1 = ex_random_tensor_1.T
print(transposed_ex_random_number_1)

ex_mult = torch.mm(ex_random_tensor, transposed_ex_random_number_1)
print(ex_mult, ex_mult.shape)

tensor([[-1.9779, -0.6450, -0.2374, -1.3645, -0.3105, -1.0532,  1.5438]])
tensor([[-1.9779],
        [-0.6450],
        [-0.2374],
        [-1.3645],
        [-0.3105],
        [-1.0532],
        [ 1.5438]])
tensor([[-0.6919],
        [ 0.0894],
        [ 3.5929],
        [-2.2049],
        [ 3.9387],
        [-0.0709],
        [10.5945]]) torch.Size([7, 1])


In [ ]:
# 3. Set the random seed to 0 and do exercises 2 & 3 over again.
RANDOM_SEED = 0
torch.manual_seed(RANDOM_SEED)

ex_random_tensor = torch.randn(7, 7)
print(ex_random_tensor, ex_random_tensor.shape)

torch.manual_seed(RANDOM_SEED)

ex_random_tensor_1 = torch.randn(1,7)
print(ex_random_tensor_1)
transposed_ex_random_number_1 = ex_random_tensor_1.T
print(transposed_ex_random_number_1)
print(ex_random_tensor == transposed_ex_random_number_1) # due to different shape yet compatibility, broadcast will happen where the (7,1) will extend to (7, 7) but will result in 'false' values.
# All False happens because broadcasting compares random floating-point numbers for exact equality, and random floats almost never match exactly — even with the same seed.
ex_mult = torch.mm(ex_random_tensor, transposed_ex_random_number_1)
print(ex_mult, ex_mult.shape)

tensor([[-1.1258, -1.1524, -0.2506, -0.4339,  0.8487,  0.6920, -0.3160],
        [-2.1152,  0.3223, -1.2633,  0.3500,  0.3081,  0.1198,  1.2377],
        [ 1.1168, -0.2473, -1.3527, -1.6959,  0.5667,  0.7935,  0.5988],
        [-1.5551, -0.3414,  1.8530,  0.7502, -0.5855, -0.1734,  0.1835],
        [ 1.3894,  1.5863,  0.9463, -0.8437, -0.6136,  0.8728,  1.0554],
        [ 0.1778, -0.2303, -0.3918,  0.5433, -0.3952,  0.2055,  0.7440],
        [ 1.5210,  3.4105, -1.5312, -1.2341,  1.8197, -0.5515, -1.3253]]) torch.Size([7, 7])
tensor([[ 1.5410, -0.2934, -2.1788,  0.5684, -1.0845, -1.3986,  0.4033]])
tensor([[ 1.5410],
        [-0.2934],
        [-2.1788],
        [ 0.5684],
        [-1.0845],
        [-1.3986],
        [ 0.4033]])
tensor([[False, False, False, False, False, False, False],
        [False, False, False, False, False, False, False],
        [False, False, False, False, False, False, False],
        [False, False, False, False, False, False, False],
        [False, False, Fa

In [ ]:
# 5. Create two random tensors of shape (3, 4) and send them both to the GPU
# (you'll need access to a GPU for this). Set torch.manual_seed(1234) when creating the tensors (this doesn't have to be the GPU random seed).
random_seed=1234
torch.cuda.manual_seed(random_seed)
A = torch.randint(1, 12, (3, 4), device='cuda')
print(A)
torch.cuda.manual_seed(random_seed)
B = torch.randint(1, 12, (3, 4), device='cuda')
print(B)
print(A == B)

# if device is not defined, nothing will happen even though we are resetting the inner state on cuda i.e. torch.cuda.manual_seed(random_seed). In order to work it, mentioning deivce='cuda' is requred and hence all values will be True. Otherwise only some values will be true when on cpu by default.

tensor([[ 9,  9,  4,  4],
        [ 8,  5,  9,  7],
        [ 5,  7,  4, 11]], device='cuda:0')
tensor([[ 9,  9,  4,  4],
        [ 8,  5,  9,  7],
        [ 5,  7,  4, 11]], device='cuda:0')
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]], device='cuda:0')


In [ ]:
# 6. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).
new_B = B.T
print(new_B)
torch.matmul(A, new_B) # GPU matrix multiplication in PyTorch requires floating-point tensors.

tensor([[ 9,  8,  5],
        [ 9,  5,  7],
        [ 4,  9,  4],
        [ 4,  7, 11]], device='cuda:0')


NotImplementedError: "addmm_cuda" not implemented for 'Long'

In [ ]:
new_A = A.type(torch.float32)
print(new_A)

newer_B = new_B.type(torch.float32)
print(newer_B)

torch.mm(new_A, newer_B)

tensor([[ 9.,  9.,  4.,  4.],
        [ 8.,  5.,  9.,  7.],
        [ 5.,  7.,  4., 11.]], device='cuda:0')
tensor([[ 9.,  8.,  5.],
        [ 9.,  5.,  7.],
        [ 4.,  9.,  4.],
        [ 4.,  7., 11.]], device='cuda:0')


tensor([[194., 181., 168.],
        [181., 219., 188.],
        [168., 188., 211.]], device='cuda:0')

In [ ]:
# 7. Find the maximum and minimum values of the output of 7.
print(torch.min(torch.mm(new_A, newer_B)))

print(torch.max(torch.mm(new_A, newer_B)))

tensor(168., device='cuda:0')
tensor(219., device='cuda:0')


In [ ]:
# 8. Find the maximum and minimum index values of the output of 7
print(torch.argmin(torch.mm(new_A, newer_B)))

print(torch.argmax(torch.mm(new_A, newer_B)))

tensor(2, device='cuda:0')
tensor(4, device='cuda:0')


In [ ]:
# 9. Make a random tensor with shape (1, 1, 1, 10) and then create a new tensor with all the 1 dimensions removed to be left with a tensor of shape (10). Set the seed to 7 when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.
torch.manual_seed(7)
new_random_tensor = torch.rand(1, 1, 1, 10)
print(new_random_tensor, new_random_tensor.shape)
torch.manual_seed(7)
newer_random_tensor = torch.squeeze(new_random_tensor)
print(newer_random_tensor, newer_random_tensor.shape)


tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])


# **Exercises**

In [2]:
import torch
scalar = torch.tensor(5.66)
scalar.shape, scalar.dtype

(torch.Size([]), torch.float32)

In [11]:
scalar.item()

5.659999847412109

In [22]:
vector = torch.tensor([7,9])
vector

tensor([7, 9])

In [23]:
vector.shape, vector.ndim

(torch.Size([2]), 1)

In [26]:
newvec = vector[1].item()

In [27]:
newvec

9

In [30]:
type(newvec)

int

In [3]:
matrix = torch.tensor([2, 7,
                       3, 6])
matrix, matrix.shape, matrix.ndim

(tensor([2, 7, 3, 6]), torch.Size([4]), 1)

In [4]:
# 2. Create a random tensor with shape (7, 7)
rand_tensor_1 = torch.randn(size=(7,7))
rand_tensor_1

tensor([[-0.8261,  0.0593,  0.7129,  0.0899,  0.2594, -1.5583, -0.5518],
        [ 0.6726,  0.4349,  1.2867,  0.1955, -1.3485,  0.5979,  0.6743],
        [-0.4270,  0.8768,  1.4263, -1.0783, -0.6351,  1.4676, -0.9811],
        [-1.2989,  0.6384, -2.2396, -0.4060,  1.2221,  0.2912,  2.0283],
        [ 1.6386,  0.2475, -0.1600, -0.0438,  0.4174, -0.6141,  0.1443],
        [-0.2040,  0.0847,  0.9042,  0.0593,  1.2889, -1.4627,  0.0707],
        [-0.2176,  1.5697,  1.1640, -0.8873, -0.0857,  1.6201, -1.1851]])

In [5]:
rand1 = torch.rand(size=(2, 4))
rand1

tensor([[0.8657, 0.8002, 0.4654, 0.4843],
        [0.2322, 0.7423, 0.7252, 0.8136]])

In [6]:
rand2 = torch.randint(low = 2, high = 7, size = (2, 4))
rand2

tensor([[3, 5, 6, 3],
        [5, 2, 3, 6]])

In [7]:
rand3 = torch.randn(size=(2, 4))
rand3

tensor([[ 0.7484, -0.0740,  0.4194, -0.8585],
        [-1.3133, -1.1866, -0.3845,  0.5320]])

In [26]:
# 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape (1, 7) (hint: you may have to transpose the second tensor).
'''
Here, we would get error as the inner dimension doesn't match for matrix multiplication.
Note: to make matrix multiplication working, the inner dimension must match and as result we get the outer dimension as result.
so shape (7,7) and shape(1, 7) won't work. We would transpose the second one in order to match the inner dimension.
'''
rand_tensor_2 = torch.randn(size=(1, 7))
matmul_result = torch.mm(rand_tensor_1, rand_tensor_2)
matmul_result



RuntimeError: mat1 and mat2 shapes cannot be multiplied (7x7 and 1x7)

In [27]:
transposed_random_tensor_2 = rand_tensor_2.T
transposed_random_tensor_2, '\n', transposed_random_tensor_2.shape

(tensor([[-1.4473],
         [-0.2039],
         [ 0.8738],
         [-0.6816],
         [ 0.6339],
         [ 0.1922],
         [ 0.0918]]),
 '\n',
 torch.Size([7, 1]))

In [28]:
matmul_resultant = rand_tensor_1 * transposed_random_tensor_2
matmul_resultant, '\n', matmul_resultant.shape

(tensor([[ 1.1956, -0.0858, -1.0318, -0.1301, -0.3755,  2.2554,  0.7986],
         [-0.1372, -0.0887, -0.2624, -0.0399,  0.2749, -0.1219, -0.1375],
         [-0.3731,  0.7661,  1.2462, -0.9422, -0.5549,  1.2823, -0.8572],
         [ 0.8853, -0.4351,  1.5265,  0.2768, -0.8330, -0.1985, -1.3825],
         [ 1.0387,  0.1569, -0.1014, -0.0278,  0.2646, -0.3893,  0.0915],
         [-0.0392,  0.0163,  0.1738,  0.0114,  0.2477, -0.2811,  0.0136],
         [-0.0200,  0.1441,  0.1069, -0.0815, -0.0079,  0.1488, -0.1088]]),
 '\n',
 torch.Size([7, 7]))

In [29]:
# 4. Set the random seed to 0 and do exercises 2 & 3 over again.
torch.manual_seed(42)
matmul_resultant_1 = rand_tensor_1 * transposed_random_tensor_2
matmul_resultant_1

tensor([[ 1.1956, -0.0858, -1.0318, -0.1301, -0.3755,  2.2554,  0.7986],
        [-0.1372, -0.0887, -0.2624, -0.0399,  0.2749, -0.1219, -0.1375],
        [-0.3731,  0.7661,  1.2462, -0.9422, -0.5549,  1.2823, -0.8572],
        [ 0.8853, -0.4351,  1.5265,  0.2768, -0.8330, -0.1985, -1.3825],
        [ 1.0387,  0.1569, -0.1014, -0.0278,  0.2646, -0.3893,  0.0915],
        [-0.0392,  0.0163,  0.1738,  0.0114,  0.2477, -0.2811,  0.0136],
        [-0.0200,  0.1441,  0.1069, -0.0815, -0.0079,  0.1488, -0.1088]])

In [30]:
# 5. Create two random tensors of shape (2, 3) and send them both to the GPU (you'll need access to a GPU for this). Set torch.manual_seed(1234) when creating the tensors (this doesn't have to be the GPU random seed).
device = 'cuda' if torch.cuda.is_available() else 'cpu'
device

'cuda'

In [31]:
torch.manual_seed(1234)

rand_tensor_2 = torch.randn(size=(2, 3))
rand_tensor_3 = torch.randn(size=(2, 3))

rand_tensor_2, '\n', rand_tensor_3

(tensor([[ 0.0461,  0.4024, -1.0115],
         [ 0.2167, -0.6123,  0.5036]]),
 '\n',
 tensor([[ 0.2310,  0.6931, -0.2669],
         [ 2.1785,  0.1021, -0.2590]]))

In [32]:
gpu_rand_tensor_2 = rand_tensor_2.to(device)
gpu_rand_tensor_3 = rand_tensor_3.to(device)
gpu_rand_tensor_2, gpu_rand_tensor_2.shape, '\n', gpu_rand_tensor_3, gpu_rand_tensor_3.shape

(tensor([[ 0.0461,  0.4024, -1.0115],
         [ 0.2167, -0.6123,  0.5036]], device='cuda:0'),
 torch.Size([2, 3]),
 '\n',
 tensor([[ 0.2310,  0.6931, -0.2669],
         [ 2.1785,  0.1021, -0.2590]], device='cuda:0'),
 torch.Size([2, 3]))

In [33]:
# 6. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

matmul_result = torch.mm(gpu_rand_tensor_2, gpu_rand_tensor_3)
matmul_result

RuntimeError: mat1 and mat2 shapes cannot be multiplied (2x3 and 2x3)

In [35]:
transposed_gpu_rand_tensor_3 = gpu_rand_tensor_3.T
transposed_gpu_rand_tensor_3

tensor([[ 0.2310,  2.1785],
        [ 0.6931,  0.1021],
        [-0.2669, -0.2590]], device='cuda:0')

In [37]:
matmul_result = torch.mm(gpu_rand_tensor_2, transposed_gpu_rand_tensor_3)
matmul_result, '\n', matmul_result.shape


(tensor([[ 0.5595,  0.4036],
         [-0.5087,  0.2792]], device='cuda:0'),
 '\n',
 torch.Size([2, 2]))

In [40]:
# 7. Find the maximum and minimum index values of the output of 6.

print(f'index value of minimum of matmul_result: {torch.argmin(matmul_result)} \n')
print(f'index value of maximum of matmul_result: {torch.argmax(matmul_result)}')

index value of minimum of matmul_result: 2 

index value of maximum of matmul_result: 0


In [43]:
# Find the maximum and minimum values of the output of 6.

print(f'minimum of matmul_result: {torch.max(matmul_result)} \n')
print(f'maximum of matmul_result: {torch.min(matmul_result)}')

minimum of matmul_result: 0.5594881176948547 

maximum of matmul_result: -0.5086870789527893


In [50]:
# Make a random tensor with shape (1, 1, 1, 10) and then create a new tensor with all the 1 dimensions removed to be left with a tensor of shape (10). Set the seed to 7 when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.
torch.manual_seed(7)

random_tensor_4 = torch.rand(size=(1, 1, 1, 10))
random_tensor_4, '\n', random_tensor_4.shape, '\n', random_tensor_4.ndim

(tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
            0.3653, 0.8513]]]]),
 '\n',
 torch.Size([1, 1, 1, 10]),
 '\n',
 4)

In [51]:
new_random_tensor_4 = random_tensor_4.squeeze()
new_random_tensor_4, '\n', new_random_tensor_4.shape, '\n', new_random_tensor_4.ndim

(tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
         0.8513]),
 '\n',
 torch.Size([10]),
 '\n',
 1)